force-app/main/default/objects/cgcloud__Account_Template__c/cgcloud__Account_Template__c.object-meta.xml
<CustomObject>
    <description>holds the details of the account template object to be used for accounts.</description>
    <label>Customer Template</label>
    <nameField>
        <label>Customer Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Promotion__c/cgcloud__Promotion__c.object-meta.xml
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <label>Advanced Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advanced Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Promotion__c/fields/TPM_Phase__c.field-meta.xml
<CustomField>
    <fullName>TPM_Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Finance Edit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Promotion__c/fields/TPM_Promotion_Submitter__c.field-meta.xml
<CustomField>
    <fullName>TPM_Promotion_Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TPM_AdvancedPromotions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Promotion_Template__c/cgcloud__Promotion_Template__c.object-meta.xml
<CustomObject>
    <description>Template for the creation of a promotion.</description>
    <label>Promotion Template</label>
    <nameField>
        <label>Promotion Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TPM_Approval__c/TPM_Approval__c.object-meta.xml
<CustomObject>
    <description>Custom object for Promotion &amp; Claim approvals</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Approvals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TPM_Approval__c/fields/TPM_Phase__c.field-meta.xml
<CustomField>
    <fullName>TPM_Phase__c</fullName>
    <description>Phase of the promotion</description>
    <label>Promotion Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preparation</fullName>
                <default>true</default>
                <label>Preparation</label>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Modeling</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>For Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Finance edit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_Approval__c/fields/TPM_Promotion__c.field-meta.xml
<CustomField>
    <fullName>TPM_Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field for Promotion</description>
    <label>Promotion</label>
    <referenceTo>cgcloud__Promotion__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TPM_Approval__c/fields/TPM_Promotion_Submitter__c.field-meta.xml
<CustomField>
    <fullName>TPM_Promotion_Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TPM_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TPM_ApprovalComponentControllerTest.cls
/*******************************************************************************************************
* @Name         : TPM_ApprovalComponentControllerTest
* @Unit Test    : TPM_ApprovalComponentControllerTest
* @Author       : PwC Team
* @Date         : 28/04/2023
* @description  : Test Class for the lwc component
				  tpmApprovalCardComponent
*******************************************************************************************************/
@isTest
public class TPM_ApprovalComponentControllerTest {
    
    static String assertStr = 'List should not be empty';
    
     /*****************************************************************************************
    * @method			testDataSetUpMethod
    * @ return     		:void
    * @param   		  
    * @description    	Test Setup method for TPM_ApprovalComponentController Class
    *****************************************************************************************/
    @testSetup
    public static void createTestData(){
        
        // Create Sales Profile Record
        String salesProfileId = TPM_TestDataUtility.getProfileId('Sales Profile');
        
        // Create a Sales Profile User Record
        User testSalesProfileUser = TPM_TestDataUtility.createTestUser(salesProfileId,'Test Sales','Profile User');
        insert testSalesProfileUser;
        
        // Create Customer Template
        cgcloud__Account_Template__c accountTemplate = TPM_TestDataUtility.createCustomerTemplate('US01');
		insert accountTemplate;
        
        // Create Account
        Account accRecord = TPM_TestDataUtility.createAccountWithTemplate('Managed Account','US01',accountTemplate.Id);
        insert accRecord;
        
        // Create Promotion Template
        cgcloud__Promotion_Template__c promotionTemplateUS01 = TPM_TestDataUtilityExtension.createPromotionTemplate();
        insert promotionTemplateUS01;
        
        // Create Promotion Record
        cgcloud__Promotion__c promotionRecord = TPM_TestDataUtilityExtension.createPromotionWithPhase(accRecord.Id,promotionTemplateUS01.Id,'Planning');
        insert promotionRecord;
        
        // Update the Promotion Record
        // Status to Submitted for Approval
        promotionRecord.TPM_Phase__c = 'Submitted For Approval';
        update promotionRecord;
        
        // Create Approval Record
        TPM_Approval__c approvalObj = new TPM_Approval__c();
        approvalObj.TPM_Promotion__c =  promotionRecord.Id;
        approvalObj.TPM_Promotion_Submitter__c = testSalesProfileUser.Id;
        approvalObj.OwnerId = testSalesProfileUser.Id;
        insert approvalObj;
        
    }
    
    /******************************************************************************************
    * @method			tpmApprovalCardComponentTest
    * @ return     		void
    * @param   		  
    * @description    	Test Method for TPM_ApprovalCardComponent Class
    * 					getPromotionRelatedApprovals()
    ******************************************************************************************/
    @isTest
    public static void tpmApprovalCardComponentTest(){
        
        // Get the created Promotion Record
        List<cgcloud__Promotion__c> promotionRecordList = [SELECT Id,
                                                           		  Name,
                                                           		  cgcloud__Slogan_Language_1__c
                                                           FROM   cgcloud__Promotion__c
                                                           WHERE  cgcloud__Slogan_Language_1__c = 'Test'
                                                           LIMIT	1];
        // Get the created Sales Profile User
        List<User> testSalesProfileUserList = [SELECT Id,
                                              		  Name,
                                               		  FirstName
                                               FROM   User
                                               WHERE  FirstName = 'Test Sales'];
        
        List<TPM_ApprovalComponentController.ApprovalWrapperClass> approvalWrapperClassList = TPM_ApprovalComponentController.getPromotionRelatedApprovals(promotionRecordList[0].Id,testSalesProfileUserList[0].Id);
        // Check If the records are there in the Wrapper Class
        System.assertEquals(false, approvalWrapperClassList.isEmpty(), assertStr);
         
    }
    
}