force-app/main/default/objects/cgcloud__Account_Plan__c/cgcloud__Account_Plan__c.object-meta.xml
<CustomObject>
    <description>Container for Account Data for one Planning Account, one Business Year and one or multiple Categories.</description>
    <label>Customer Business Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Business_Year__c/cgcloud__Business_Year__c.object-meta.xml
<CustomObject>
    <description>This object holds the attributes of the Business Year</description>
    <label>Business Year</label>
    <nameField>
        <displayFormat>BY-{000000}</displayFormat>
        <label>Business Year Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/cgcloud__Category__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Category__c</fullName>
    <description>Product category.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>All Products</fullName>
                <default>true</default>
                <label>All Products</label>
            </value>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Chips</fullName>
            </value>
            <value>
                <fullName>Detergent</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Hygiene</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_Trigger_Config_Settings__c/TPM_Trigger_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TPM_Trigger Config Settings</label>
</CustomObject>

force-app/main/default/classes/TPM_CBPCategoryTriggerTest.cls
/*******************************************************************************************************
* @name         : TPM_CBPCategoryTriggerTest
* @author       : PwC Team
* @date         : 12/23/2022
* @description  : Test Class for TPM_CBPCategoryTrigger
*******************************************************************************************************/
@isTest
public class TPM_CBPCategoryTriggerTest {
    
    /******************************************************************************************
    * @method			testDataSetUpMethod
    * @ return     		:void
    * @param   		  
    * @description    	Setup method for user test class
    ******************************************************************************************/
    @testSetup static void testDataSetUpMethod() {
        List<TPM_Trigger_Config_Settings__c> triggerConfigSettingList = TPM_TestDataUtility.createTriggerConfigSetting();
        insert triggerConfigSettingList;
        User userObj = TPM_TestDataUtility.createUser('System Administrator');
        insert userObj;
        
        // Create Test Product Record
        TPM_TestDataUtility.createProductData('US01','Product','Category',1,true);
        
        // Create Test Account Record
        List<Account> accList = TPM_TestDataUtility.createAccounts(1);
        insert accList;
        
        // Get the Created Account Record
        Account createdAccObj = [SELECT Id,
                                 		Name
                                 FROM   Account 
                                 WHERE 	Name = 'Test Customer1'];

        // Get the Created Product Record
        Product2 createdprodObj = [SELECT Id,
                           		   Name 
                            FROM   Product2
                           	WHERE  Name = 'US01 Product Test Product 1'];
        
        // Create Test SVF Record
        cgcloud__Account_Plan__c testSVFObj = new cgcloud__Account_Plan__c();
        testSVFObj.cgcloud__Business_Year__c = 2024;
        testSVFObj.cgcloud__Account__c = createdAccObj.Id;
        insert testSVFObj;

        // Create Test SVF Category Record
        cgcloud__Account_Plan_Category__c testAccPlanCat = new cgcloud__Account_Plan_Category__c();
        testAccPlanCat.cgcloud__Category__c = createdprodObj.Id;
        testAccPlanCat.cgcloud__Account_Plan__c = testSVFObj.Id;
        insert testAccPlanCat;

    }
    
     /******************************************************************************************
    * @method			testCBPCategory
    * @ return     		:void
    * @param   		  
    * @description    	test method for CBP Category Trigger
    ******************************************************************************************/
    
     @isTest
    public static void testCBPCategory() {
        
        // Get the Created Product Record 
        Product2 createdprodObj = [SELECT Id,
                           		   Name 
                            FROM   Product2
                           	WHERE  Name = 'US01 Product Test Product 1'];
        
        // Get the Created SVF Category Record
        cgcloud__Account_Plan_Category__c createdSVFCategoryObj = [SELECT Id,
                                                                   		  Name,
                                                                   		  cgcloud__Category__c
                                                                   FROM   cgcloud__Account_Plan_Category__c
                                                                   WHERE  cgcloud__Category__c =: createdprodObj.Id];
        
        // Update Test SVF Category
        createdSVFCategoryObj.cgcloud__Manual_Calculation_Input__c = 'Updating cgcloud__Manual_Calculation_Input__c field Value';
        update createdSVFCategoryObj;
        
        System.assertEquals('Updating cgcloud__Manual_Calculation_Input__c field Value', createdSVFCategoryObj.cgcloud__Manual_Calculation_Input__c, 'Field Value is not updated');
        
    }

}