force-app/main/default/objects/cgcloud__Week_Day_Share_Profile__c/cgcloud__Week_Day_Share_Profile__c.object-meta.xml
<CustomObject>
    <description>Contains statistical profiles how weekly data is distributed between different days of a week.</description>
    <label>Week Day Share Profile</label>
    <nameField>
        <displayFormat>WDSP-{0000000}</displayFormat>
        <label>Week Day Share Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Week Day Share Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TPM_Initial_Data_Load__mdt/TPM_Initial_Data_Load__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata for initial Loads</description>
    <label>TPM Initial Data Load</label>
    <pluralLabel>TPM Initial Data Load</pluralLabel>
</CustomObject>

force-app/main/default/objects/TPM_Initial_Data_Load__mdt/fields/TPM_Friday__c.field-meta.xml
<CustomField>
    <fullName>TPM_Friday__c</fullName>
    <description>Friday Value</description>
    <label>Friday</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TPM_Initial_Data_Load__mdt/fields/TPM_Monday__c.field-meta.xml
<CustomField>
    <fullName>TPM_Monday__c</fullName>
    <description>Monday Value for Weekday profile</description>
    <label>Monday</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TPM_Initial_Data_Load__mdt/fields/TPM_ObjectName__c.field-meta.xml
<CustomField>
    <fullName>TPM_ObjectName__c</fullName>
    <description>Object Name</description>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>cgcloud__Business_Year__c</fullName>
                <default>true</default>
                <label>cgcloud__Business_Year__c</label>
            </value>
            <value>
                <fullName>cgcloud__Account_Template__c</fullName>
            </value>
            <value>
                <fullName>cgcloud__Metadata_Wizard_Configuration__c</fullName>
            </value>
            <value>
                <fullName>cgcloud__Week_Day_Share_Profile__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_Initial_Data_Load__mdt/fields/TPM_Saturday__c.field-meta.xml
<CustomField>
    <fullName>TPM_Saturday__c</fullName>
    <description>Saturday Value</description>
    <label>Saturday</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TPM_Initial_Data_Load__mdt/fields/TPM_Sunday__c.field-meta.xml
<CustomField>
    <fullName>TPM_Sunday__c</fullName>
    <description>Sunday Value</description>
    <label>Sunday</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TPM_Initial_Data_Load__mdt/fields/TPM_Thursday__c.field-meta.xml
<CustomField>
    <fullName>TPM_Thursday__c</fullName>
    <description>Thursday Value</description>
    <label>Thursday</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TPM_Initial_Data_Load__mdt/fields/TPM_Tuesday__c.field-meta.xml
<CustomField>
    <fullName>TPM_Tuesday__c</fullName>
    <description>Tuesday Value</description>
    <label>Tuesday</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TPM_Initial_Data_Load__mdt/fields/TPM_Wednesday__c.field-meta.xml
<CustomField>
    <fullName>TPM_Wednesday__c</fullName>
    <description>Wednesday Value</description>
    <label>Wednesday</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TPM_InitialDataLoadWeekday.cls
/*******************************************************************************************************
* @Name         : TPM_InitialDataLoadWeekday
* @Unit Test    : TPM_InitialDataLoadTest
* @Author       : PwC Team
* @Date         : December 22, 2022
* @description  : This Apex is used for automating data load in for Week Day Profile.
*******************************************************************************************************
Change History Story      Modified by               Date                          Desc

*******************************************************************************************************/
public with sharing class TPM_InitialDataLoadWeekday {

     /*********************************************************************************
    * @method         : TPM_InitialDataLoadWeekday
    * @description    : Constructor
    **********************************************************************************/
    @SuppressWarnings('PMD.EmptyStatementBlock')
    private TPM_InitialDataLoadWeekday(){


    }
   
     /*********************************************************************************
    * @method         : weekDayProfileLoad
    * @param            orgVal
    * @description    : Fetch data from Custom Metadata and insert weekday profile records
    **********************************************************************************/
    public static void weekDayProfileLoad(Set<String> orgVal){
        //Fetch data from custom meta data type and insert record for weekday profile
        //Map of weekday sales Org and Week Day Record id
      Map<String,String> existingWeekDayProfileMap = TPM_DataLoadAutomationUtil.returnWeekDayProfile(orgVal);
      List<cgcloud__Week_Day_Share_Profile__c> weekDayRecordList = new List<cgcloud__Week_Day_Share_Profile__c>();
      TPM_Initial_Data_Load__mdt weekDayValues = [SELECT Id,
                                                  TPM_Monday__c,
                                                  TPM_Tuesday__c,
                                                  TPM_Wednesday__c,
                                                  TPM_Thursday__c,
                                                  TPM_Friday__c,
                                                  TPM_Saturday__c,
                                                  TPM_Sunday__c 
                                                  FROM TPM_Initial_Data_Load__mdt 
                                                  WHERE TPM_ObjectName__c = :TPM_AutomationConstantUtilityClass.WEEKDAY_PROFILE
                                                  AND DeveloperName = :TPM_AutomationConstantUtilityClass.WEEKDAY_PROFILE_VALUES 
                                                  WITH SECURITY_ENFORCED];
      for(String orgValRec : orgVal){
        //If record already exists skip creation of records
        //If Weekday record already exists for the org then skip creation of records 
          if(!existingWeekDayProfileMap.containsKey(orgValRec)){
              cgcloud__Week_Day_Share_Profile__c weekday = new cgcloud__Week_Day_Share_Profile__c();
              weekday.cgcloud__Sales_Org__c= orgValRec;
              weekday.cgcloud__Description_Language_1__c = orgValRec+TPM_AutomationConstantUtilityClass.WEEKDAY_SHARE_PROFILE;
              weekday.cgcloud__Monday__c = weekDayValues.TPM_Monday__c;
              weekday.cgcloud__Tuesday__c = weekDayValues.TPM_Tuesday__c;
              weekday.cgcloud__Wednesday__c = weekDayValues.TPM_Wednesday__c;
              weekday.cgcloud__Thursday__c = weekDayValues.TPM_Thursday__c;
              weekday.cgcloud__Friday__c = weekDayValues.TPM_Friday__c;
              weekday.cgcloud__Saturday__c = weekDayValues.TPM_Saturday__c;
              weekday.cgcloud__Sunday__c = weekDayValues.TPM_Sunday__c;
              weekDayRecordList.add(weekday);
            }
    }

    if(!weekDayRecordList.isempty() && Schema.sObjectType.cgcloud__Week_Day_Share_Profile__c.isCreateable()){
    //insert weekday profile records
        TPM_InitialDataLoadHandleError.createAndHandleError(weekDayRecordList,TPM_AutomationConstantUtilityClass.WEEKDAYPROFILELOAD);
      }
    } 
  }