force-app/main/default/objects/TPM_Trigger_Config_Settings__c/TPM_Trigger_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TPM_Trigger Config Settings</label>
</CustomObject>

force-app/main/default/objects/User/fields/TPM_Persona__c.field-meta.xml
<CustomField>
    <fullName>TPM_Persona__c</fullName>
    <defaultValue>(&apos;Account Executive&apos;)</defaultValue>
    <description>Persona of the User to derive users accessibility</description>
    <label>Persona</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Business Administrator</fullName>
            </value>
            <value>
                <fullName>Data and Analytics</fullName>
            </value>
            <value>
                <fullName>Trade Payments</fullName>
            </value>
            <value>
                <fullName>Sales Director</fullName>
            </value>
            <value>
                <fullName>Sales Finance</fullName>
            </value>
            <value>
                <fullName>Sales Managers</fullName>
            </value>
            <value>
                <fullName>Account Executive</fullName>
                <default>true</default>
                <label>Account Executive</label>
            </value>
            <value>
                <fullName>Product Supply Chain</fullName>
            </value>
            <value>
                <fullName>External Account Executive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/TPM_Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>TPM_Sales_Org__c</fullName>
    <description>Sales Orgs that user has access to</description>
    <label>Available Sales Organization</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>cgcloud__Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/cgcloud__Sales_Org.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US01</fullName>
    </customValue>
    <customValue>
        <fullName>IT01</fullName>
    </customValue>
    <customValue>
        <fullName>US08</fullName>
        <isActive>false</isActive>
        <label>US08</label>
    </customValue>
    <customValue>
        <fullName>US09</fullName>
        <isActive>false</isActive>
        <label>US09</label>
    </customValue>
    <customValue>
        <fullName>IT02</fullName>
        <isActive>false</isActive>
        <label>IT02</label>
    </customValue>
    <customValue>
        <fullName>0000</fullName>
        <isActive>false</isActive>
        <label>0000</label>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
        <isActive>false</isActive>
        <label>0003</label>
    </customValue>
    <customValue>
        <fullName>0002</fullName>
        <isActive>false</isActive>
        <label>0002</label>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
        <isActive>false</isActive>
        <label>0001</label>
    </customValue>
    <description>Sales Org value</description>
    <masterLabel>Sales Org</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TPM_UserTriggerTest.cls
/*******************************************************************************************************
* @name         : TPM_UserTriggerTest
* @author       : PwC Team
* @date         : 12/23/2022
* @description  : Test Class for user trigger
*******************************************************************************************************/
@isTest
public class TPM_UserTriggerTest {

    static String assertStr = 'List should not be empty';
    
    /******************************************************************************************
    * @method			testDataSetUpMethod
    * @ return     		:void
    * @param   		  
    * @description    	Setup method for user test class
    ******************************************************************************************/
    @testSetup static void testDataSetUpMethod() {
        List<TPM_Trigger_Config_Settings__c> triggerConfigSettingList = TPM_TestDataUtility.createTriggerConfigSetting();
        insert triggerConfigSettingList;
        User userObj = TPM_TestDataUtility.createUser('System Administrator');
        insert userObj;
    }
    
 /******************************************************************************************
    * @method			testUserUpdateDeactive
    * @ return     		:void
    * @param   		  
    * @description    	test method for user trigger helper
    ******************************************************************************************/
    
     @isTest
    public static void testUserUpdateDeactive() {
        User userobj = [SELECT Id,TPM_Persona__c,isactive FROM user WHERE Alias='standt' LIMIT 1];
        userobj.isactive = false;
        update userobj;
        userobj.isactive= true;
        update userobj;
        List<User> userObjList = [SELECT Id,TPM_Persona__c,isactive FROM user WHERE Alias='standt' LIMIT 1];
       system.assert(!userObjList.isEmpty(),assertStr);
        
        
    }
    
    /******************************************************************************************
    * @method			testUserUpdateActive
    * @ return     		:void
    * @param   		  
    * @description    	test method for user trigger helper
    ******************************************************************************************/
    @isTest
    public static void testUserUpdateActive() {
        User userobj = [SELECT Id,TPM_Persona__c,isactive,Alias FROM user WHERE Alias='standt' LIMIT 1];
        userobj.isactive = true;
        update userobj;
        List<User> userObjList = [SELECT Id,TPM_Persona__c,isactive FROM user WHERE Alias='standt' LIMIT 1];
       system.assert(!userObjList.isEmpty(),assertStr);
        
        
    }

     /******************************************************************************************
    * @method			testUserUpdateHandleExcep
    * @ return     		:void
    * @param   		  
    * @description    	test method for user trigger helper
    ******************************************************************************************/
    
    @isTest
    public static void testUserUpdateHandleExcep() {
        TPM_UserTriggerHandler tpmTriggerHandler = new TPM_UserTriggerHandler();
		List<Id> userIdList = new List<Id>();
        Map<Id,Sobject> newMapUser = new map<Id,Sobject>();
        User userobj = [SELECT Id,TPM_Persona__c,isactive,Alias FROM user WHERE Alias='standt' LIMIT 1];
        userobj.isactive = true;
        userobj.Alias=userobj.Alias+'123456';
        userIdList.add(userobj.Id);
        newMapUser.put(userobj.id,userobj);
        TPM_UserTriggerHelper.assignUserToGroup(userIdList);
        TPM_UserTriggerHelper.createUserSetting(newMapUser);
        tpmTriggerHandler.afterInsert(newMapUser);
        List<User> userObjList = [SELECT Id,TPM_Persona__c,isactive FROM user WHERE Alias='standt' LIMIT 1];
       system.assert(!userObjList.isEmpty(),assertStr);
     }
    
     /******************************************************************************************
    * @method			testUserUpdateHandleExcep2
    * @ return     		:void
    * @param   		  
    * @description    	test method for user trigger helper
    ******************************************************************************************/
    /*@isTest
    public static void testUserUpdateHandleExcep2() {
        
        TPM_TriggerDispatcher.createHandler(TPM_Utils.class);
        List<User> userObjList = [SELECT Id,TPM_Persona__c,isactive FROM user WHERE Alias='standt' LIMIT 1];
       system.assert(!userObjList.isEmpty(),assertStr);
    }*/
    
    /******************************************************************************************
    * @method			testUserUpdateName
    * @ return     		:void
    * @param   		  
    * @description    	test method for user trigger helper 
    ******************************************************************************************/
    @isTest
    public static void testUserUpdateName() {
        User userobj = [SELECT Id,lastName ,TPM_Persona__c,isactive FROM user WHERE Alias='standt' LIMIT 1];
        userobj.lastName = userobj.lastName+'New';
        update userobj;
        List<User> userObjList = [SELECT Id,TPM_Persona__c,isactive FROM user WHERE Alias='standt' LIMIT 1];
       system.assert(!userObjList.isEmpty(),assertStr);
        
    }

    /******************************************************************************************
    * @method			testUserChangePersona
    * @ return     		:void
    * @param   		  
    * @description    	test method for user trigger helper
    ******************************************************************************************/
    @isTest
    public static void testUserChangePersona() {
        User userobj = [SELECT Id,TPM_Persona__c,isactive FROM user WHERE Alias='standt' LIMIT 1];
        userobj.TPM_Persona__c = 'System Administrator';
        update userobj;
        List<User> userObjList = [SELECT Id,TPM_Persona__c,isactive FROM user WHERE Alias='standt' LIMIT 1];
       system.assert(!userObjList.isEmpty(),assertStr);
        
        
    }
    
    /******************************************************************************************
    * @method			testUserHandlerMethod
    * @ return     		:void
    * @param   		  
    * @description    	test method for user trigger helper
    ******************************************************************************************/
    @isTest
    public static void testUserHandlerMethod() {
        List<Sobject> sobectList = new List<Sobject>();
        Map<Id, SObject> newMapParam = new  Map<Id, SObject>();
        Map<Id, SObject> oldMapParam = new  Map<Id, SObject>();
        TPM_UserTriggerHandler tpmTriggerHandler = new TPM_UserTriggerHandler();
        tpmTriggerHandler.bulkBefore();
            tpmTriggerHandler.beforeInsert(sobectList);
            tpmTriggerHandler.beforeUpdate(newMapParam,oldMapParam);
            tpmTriggerHandler.beforeDelete(oldMapParam);
            tpmTriggerHandler.afterDelete(oldMapParam);
            tpmTriggerHandler.afterUnDelete(sobectList);
        List<User> userObjList = [SELECT Id,TPM_Persona__c,isactive FROM user WHERE Alias='standt' LIMIT 1];
       system.assert(!userObjList.isEmpty(),assertStr);
        
        
        
    }
    
    /******************************************************************************************
    * @method			testSalesOrgChange
    * @ return     		:void
    * @param   		  
    * @description    	test method for sales org change update
    ******************************************************************************************/
    @isTest
    public static void testSalesOrgChange() {
        
        List<User> userobjList = [SELECT Id,lastName ,TPM_Sales_Org__c,isactive FROM user WHERE Alias='standt' AND TPM_Sales_Org__c != null LIMIT 1];
        userobjList[0].TPM_Sales_Org__c = 'IT01';
        update userobjList[0];
        system.assert(!userObjList.isEmpty(),assertStr);

        
        
    }

}