force-app/main/default/objects/TPM_QueryDefinition__mdt/TPM_QueryDefinition__mdt.object-meta.xml
<CustomObject>
    <label>Query Definition</label>
    <pluralLabel>Query Definition</pluralLabel>
</CustomObject>

force-app/main/default/objects/TPM_QueryDefinition__mdt/fields/TPM_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>TPM_BatchSize__c</fullName>
    <label>Batch Size</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TPM_CustomerHierarchyScheduler.cls
/*******************************************************************************************************
* @Name           TPM_CustomerHierarchyScheduler
* @author         PwC Team
* @date           January 19, 2023
* @description    Scheduler Apex is used for customer hierarchy staging batch.
*******************************************************************************************************
Change History Story      Modified by               Date                          Desc

*******************************************************************************************************/
public with sharing class TPM_CustomerHierarchyScheduler implements Schedulable {
    
    /*******************************************************************************************
    * @method          : execute
    * @param             sch
    * @description     : method to schedule execution for TPM_CustomerHierarchyBatch batch
    ********************************************************************************************/
    public void execute(SchedulableContext sch) {
        Integer batchSize = TPM_ConstantsUtility.NUMBER_200;
        
        TPM_QueryDefinition__mdt batchQueryMdt = TPM_QueryDefinition__mdt.getInstance(TPM_ConstantsUtility.BATCH_CUSTOMERHIERARCHY_AUTOMATION);
        if(String.isNotBlank(batchQueryMdt.TPM_BatchSize__c)){
            batchSize = Integer.valueOf(batchQueryMdt.TPM_BatchSize__c);
        }
        
        TPM_CustomerHierarchyBatch custHierarchyBatch = new TPM_CustomerHierarchyBatch();       
        database.executeBatch(custHierarchyBatch, batchSize);       
    }
}