force-app/main/default/objects/TPM_QueryDefinition__mdt/TPM_QueryDefinition__mdt.object-meta.xml
<CustomObject>
    <label>Query Definition</label>
    <pluralLabel>Query Definition</pluralLabel>
</CustomObject>

force-app/main/default/objects/TPM_QueryDefinition__mdt/fields/TPM_BatchSize__c.field-meta.xml
<CustomField>
    <fullName>TPM_BatchSize__c</fullName>
    <label>Batch Size</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TPM_AssortmentCreationScheduler.cls
/*******************************************************************************************************
* @Name         : TPM_AssortmentCreationScheduler
* @testclass    :  TPM_AssortmentCreationBatchTest
* @Author       : PwC Team
* @date         : February 7, 2023
* @description  : Schedulable Apex is used to schedule assortment creation for account records.
*******************************************************************************************************
Change History Story      Modified by               Date                          Desc

*******************************************************************************************************/

public without sharing class TPM_AssortmentCreationScheduler implements Schedulable {
    
    /******************************************************************************************
    * @method			 execute
    * @param			 scon
    * @description		 Schedulable execute method.
    ******************************************************************************************/ 
    public void execute(SchedulableContext scon) {
        
        Integer batchSize = TPM_ConstantsUtility.NUMBER_200;

        // To fetch the batch size from TPM_QueryDefinition__mdt record.
        TPM_QueryDefinition__mdt batchQueryMdt = TPM_QueryDefinition__mdt.getInstance(TPM_ConstantsUtility.BATCH_ASSORTMENT_CREATION);

        if(batchQueryMdt != null && String.isNotBlank(batchQueryMdt.TPM_BatchSize__c)){
            batchSize = Integer.valueOf(batchQueryMdt.TPM_BatchSize__c);
        }
        
        TPM_AssortmentCreationBatch assortmentCreation = new TPM_AssortmentCreationBatch();
        
        // Call the batch class to execute.
        Database.executeBatch(assortmentCreation, batchSize);
   }
    
}