force-app/main/default/objects/TPM_Customer_Hierarchy_Staging__c/TPM_Customer_Hierarchy_Staging__c.object-meta.xml
<CustomObject>
    <description>Object that will serve as the staging table for Customer Hierarchy records received from Performance Analyzer</description>
    <label>Customer Hierarchy Staging</label>
    <nameField>
        <displayFormat>CH-{000000}</displayFormat>
        <label>Customer Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Hierarchy Staging</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TPM_Logger__c/TPM_Logger__c.object-meta.xml
<CustomObject>
    <label>Logger</label>
    <nameField>
        <displayFormat>DUR-{000000}</displayFormat>
        <label>Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logger</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_Account__c.field-meta.xml
<CustomField>
    <fullName>TPM_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Holds Account Info. for Customer Extension Batch</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Logger</relationshipLabel>
    <relationshipName>Logger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_ClassName__c.field-meta.xml
<CustomField>
    <fullName>TPM_ClassName__c</fullName>
    <description>Holds exception/error thrown apex class name.</description>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_ComponentName__c.field-meta.xml
<CustomField>
    <fullName>TPM_ComponentName__c</fullName>
    <description>Holds exception/error thrown component (LWC) name.</description>
    <label>Component Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_Customer_Hierarchy_Staging__c.field-meta.xml
<CustomField>
    <fullName>TPM_Customer_Hierarchy_Staging__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Hierarchy Staging</label>
    <referenceTo>TPM_Customer_Hierarchy_Staging__c</referenceTo>
    <relationshipLabel>Logger</relationshipLabel>
    <relationshipName>Logger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>TPM_ExceptionMessage__c</fullName>
    <description>Holds exception/error message.</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>TPM_ExceptionType__c</fullName>
    <description>Holds Exception / Error Type.</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_FlowName__c.field-meta.xml
<CustomField>
    <fullName>TPM_FlowName__c</fullName>
    <description>Holds Business flow name.</description>
    <label>Flow Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_GUID__c.field-meta.xml
<CustomField>
    <fullName>TPM_GUID__c</fullName>
    <description>Holds recordID / externalID for error/exceptions</description>
    <externalId>true</externalId>
    <label>GUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_LogLevel__c.field-meta.xml
<CustomField>
    <fullName>TPM_LogLevel__c</fullName>
    <description>Hold logging level for tracking.</description>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fatal</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_MethodName__c.field-meta.xml
<CustomField>
    <fullName>TPM_MethodName__c</fullName>
    <description>Holds exception/error thrown Apex class Method/ (LWC) JS Function name.</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_Product__c.field-meta.xml
<CustomField>
    <fullName>TPM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Holds Product Info. for Product Template Batch</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Logger</relationshipLabel>
    <relationshipName>Logger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_Product_Hierarchy_Staging__c.field-meta.xml
<CustomField>
    <fullName>TPM_Product_Hierarchy_Staging__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Hierarchy Staging</label>
    <referenceTo>TPM_Product_Hierarchy_Staging__c</referenceTo>
    <relationshipLabel>Logger</relationshipLabel>
    <relationshipName>Logger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_RecordName__c.field-meta.xml
<CustomField>
    <fullName>TPM_RecordName__c</fullName>
    <description>Holds exception/error from Record name.</description>
    <label>Record Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>TPM_StackTrace__c</fullName>
    <description>Use this to record complete error message.</description>
    <label>StackTrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TPM_Product_Hierarchy_Staging__c/TPM_Product_Hierarchy_Staging__c.object-meta.xml
<CustomObject>
    <description>Object that will serve as the staging table for Product Hierarchy records received from Performance Analyzer</description>
    <label>Product Hierarchy Staging</label>
    <nameField>
        <displayFormat>PH-{000000}</displayFormat>
        <label>Product Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Hierarchy Staging</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TPM_LoggerException.cls
/*******************************************************************************************************
  @Name           TPM_LoggerException
  @testclass      TPM_LoggerExceptionTest
  @Author         PwC Team
  @date           December 6, 2022
  @description    This Apex is used for error logging framework to record exceptions/erorrs in Business flows.
*******************************************************************************************************
Change History Story      Modified by               Date                          Desc

*******************************************************************************************************/

public without sharing class TPM_LoggerException extends Exception {
    /*used to avoid recursion*/
    private static Boolean isRunOnce = false;			
    
    /******************************************
	  @method          log 
	  @description     Use to trigger error log from diff components
      @param           logRecords
	********************************************/
    public static void log(List<LogsWrapper> logRecords) {							
        try {
            logErrors(logRecords);
        }
        catch(Exception excep) {
            if(!isRunOnce) {
                isRunOnce = true;
                LogsWrapper logNew = new LogsWrapper();
                logNew.exceptionObj = excep; logNew.flow = TPM_ConstantsUtility.ERROR_MODULE; 
                /*reWriting errors from error module itself (when somthing goes wrong creating error/exception details in SF)*/
                log(new List<LogsWrapper>{logNew});	
            }
        }                 
    }
    
    /******************************************
	  @method          logErrors 
	  @description     Use to write exceptions as SF record in TPM_Logger__c Object
      @param           logInfos
	********************************************/
    public static void logErrors(List<LogsWrapper> logInfos) {
        List<TPM_Logger__c> logsCollection = new List<TPM_Logger__c>();
        
        for(LogsWrapper logs : logInfos) {
            TPM_Logger__c logger = new TPM_Logger__c();
            logger.TPM_FlowName__c = logs.flow;
            logger.TPM_LogLevel__c = logs.logLevel;
            logger.TPM_GUID__c = logs.guid;
            logger.TPM_ClassName__c = logs.className;
            logger.TPM_MethodName__c = logs.methodName;
            logger.TPM_ComponentName__c = logs.cmpName;
            logger.TPM_RecordName__c = logs.recordName;
            logger.TPM_Account__c = logs.accountID;
            logger.TPM_Product__c = logs.productID;
            logger.TPM_Product_Hierarchy_Staging__c = logs.productHSID;

            // PBI-1606 : Added to populate CHS lookup.
            logger.TPM_Customer_Hierarchy_Staging__c = logs.customerHSID;
            
            //when it's not exception OR database.error [type] then pass custom error message
            if(logs.errorMessage != null) {
                logger.TPM_ExceptionMessage__c = logs.errorMessage;
            }
            
            if(logs.errors != null && !logs.errors.isEmpty()) {
                String errorMsg = '';
                String errorType = '';
                String stackTrace = '';
                for(Database.Error err :logs.errors) {
                    errorMsg += err.getMessage();
                    errorType += String.valueOf(err.getStatusCode());
                    stackTrace += String.valueOf(err.getMessage()+' \n '+err.getFields()); 
                }
                logger.TPM_ExceptionMessage__c = errorMsg;
                logger.TPM_ExceptionType__c = errorType;
                logger.TPM_StackTrace__c = stackTrace; 
            } else if(logs.exceptionObj != null){
                String stackTrace = logs.exceptionObj.getStackTraceString().substringBefore('\n');
                String className = stackTrace.substringAfter('.').substringBefore('.');
                logger.TPM_ClassName__c = className;
                logger.TPM_MethodName__c = stackTrace.substringBefore(':').substringAfter(className).substringAfter('.'); 
                logger.TPM_ExceptionType__c = logs.exceptionObj.getTypeName();
                logger.TPM_ExceptionMessage__c = logs.exceptionObj.getMessage();
                logger.TPM_StackTrace__c = String.valueOf(logs.exceptionObj) + ' at Line Number : ' + String.valueOf(logs.exceptionObj.getLineNumber()); 
            }
            logsCollection.add(logger);
        }
        insert logsCollection;   
    }

    /*******************************************************************************************************
     @description    LogsWrapper (Custom datatype collection for logs info.)
	 *               errors (List of batch database dml errors), className (apex class name), methodName (apex class name),
	 *			     exceptionObj (Instance of Exception object), flow (Business flow), logLevel (can be Fatal, Error, Warn),
	 *			     guid (recordID/externalID), cmpName (Aura/LWC/Vf name), recordName (SF Record Name e.g.: SalesOrg Name),
     *               accountID (Account Lookup for CustomerExtn Batch), productID (Product Lookup for ProductTemplateExtn Batch),
     * 			     errorMessage (Custom error message string to log)
    *******************************************************************************************************/

    public class LogsWrapper {
        /*For BatchClass/SaveResult Only starts*/
        public List<Database.Error> errors;			
        public String className;					
        public String methodName;					
        /*ends*/
        public Exception exceptionObj;				
        public String flow;							
        public String logLevel;						
        public String guid;		
        public String cmpName;
        public String recordName;
        public String accountID;
        public String productID;
        public String errorMessage;
        public String productHSID;

        // PBI-1606 : Added to populate CHS lookup.
        public String customerHSID;
    }
    
}