force-app/main/default/objects/cgcloud__Promotion__c/cgcloud__Promotion__c.object-meta.xml
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <label>Advanced Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advanced Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Promotion__c/fields/TPM_Promotion_Submitter__c.field-meta.xml
<CustomField>
    <fullName>TPM_Promotion_Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TPM_AdvancedPromotions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Promotion_Template__c/cgcloud__Promotion_Template__c.object-meta.xml
<CustomObject>
    <description>Template for the creation of a promotion.</description>
    <label>Promotion Template</label>
    <nameField>
        <label>Promotion Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Promotion_Template__c/fields/TPM_Type__c.field-meta.xml
<CustomField>
    <fullName>TPM_Type__c</fullName>
    <description>Type of TPM Promotion</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Tactic__c/fields/cgcloud__Compensation_Model__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Compensation_Model__c</fullName>
    <description>Which compensation model should be used for a tactic</description>
    <inlineHelpText>Rule to calculate promotion spend.</inlineHelpText>
    <label>Compensation Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LumpSum</fullName>
                <default>true</default>
                <label>LumpSum</label>
            </value>
            <value>
                <fullName>WeeklyLumpSum</fullName>
            </value>
            <value>
                <fullName>PerCase</fullName>
                <label>PerPack</label>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Tactic__c/fields/cgcloud__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Payment_Method__c</fullName>
    <description>Which payment method should be used for a tactic</description>
    <label>Claim Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deduction</fullName>
                <default>true</default>
                <label>Deduction</label>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>OnInvoice</fullName>
            </value>
            <value>
                <fullName>OffInvoice</fullName>
            </value>
            <value>
                <fullName>OI</fullName>
            </value>
            <value>
                <fullName>Billback/Retrospective</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Tactic__c/fields/TPM_Depth_of_Deal__c.field-meta.xml
<CustomField>
    <fullName>TPM_Depth_of_Deal__c</fullName>
    <description>Calculates the anticipated spend for post event comparison purposes</description>
    <label>Depth of Deal %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/cgcloud__Tactic__c/fields/TPM_Payment_Info__c.field-meta.xml
<CustomField>
    <fullName>TPM_Payment_Info__c</fullName>
    <description>The payment information for this tactic</description>
    <label>Payment Info</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Tactic__c/fields/TPM_Redemption_Pct__c.field-meta.xml
<CustomField>
    <fullName>TPM_Redemption_Pct__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Redemption %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/cgcloud__Tactic__c/fields/TPM_Volume_Basis__c.field-meta.xml
<CustomField>
    <fullName>TPM_Volume_Basis__c</fullName>
    <label>Volume Basis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipment</fullName>
                <default>true</default>
                <label>Shipment</label>
            </value>
            <value>
                <fullName>Consumption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_Approval__c/TPM_Approval__c.object-meta.xml
<CustomObject>
    <description>Custom object for Promotion &amp; Claim approvals</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Approvals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TPM_Approval__c/fields/TPM_Promotion__c.field-meta.xml
<CustomField>
    <fullName>TPM_Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field for Promotion</description>
    <label>Promotion</label>
    <referenceTo>cgcloud__Promotion__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TPM_Approval__c/fields/TPM_Promotion_Submitter__c.field-meta.xml
<CustomField>
    <fullName>TPM_Promotion_Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TPM_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TPM_Approval__c/fields/TPM_Status__c.field-meta.xml
<CustomField>
    <fullName>TPM_Status__c</fullName>
    <description>Status of the Approval</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted for Approval</fullName>
                <default>true</default>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_Approval__c/fields/TPM_Type__c.field-meta.xml
<CustomField>
    <fullName>TPM_Type__c</fullName>
    <description>Type of TPM Promotion</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TPM_Approval_Tactics__c/TPM_Approval_Tactics__c.object-meta.xml
<CustomObject>
    <description>Approval Tactics object is a child for approval object</description>
    <label>Approval Tactics</label>
    <nameField>
        <displayFormat>CT-{00000}</displayFormat>
        <label>Approval Tactics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Tactics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TPM_Approval_Tactics__c/fields/TPM_Approval__c.field-meta.xml
<CustomField>
    <fullName>TPM_Approval__c</fullName>
    <description>Child Object of Approval Object</description>
    <label>Approval</label>
    <referenceTo>TPM_Approval__c</referenceTo>
    <relationshipLabel>Approval Tactics</relationshipLabel>
    <relationshipName>Approval_Tactics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TPM_Approval_Tactics__c/fields/TPM_Depth_of_Deal__c.field-meta.xml
<CustomField>
    <fullName>TPM_Depth_of_Deal__c</fullName>
    <description>Calculates the anticipated spend for post event comparison purposes</description>
    <label>Depth of Deal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TPM_Approval_Tactics__c/fields/TPM_Payment_Info__c.field-meta.xml
<CustomField>
    <fullName>TPM_Payment_Info__c</fullName>
    <description>The payment information for this tactic</description>
    <label>Payment Info</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_Approval_Tactics__c/fields/TPM_Volume_Basis__c.field-meta.xml
<CustomField>
    <fullName>TPM_Volume_Basis__c</fullName>
    <label>Volume Basis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Consumption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_FieldsMapping__mdt/TPM_FieldsMapping__mdt.object-meta.xml
<CustomObject>
    <label>Field Mapping</label>
    <pluralLabel>Fields Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/TPM_FieldsMapping__mdt/fields/Lookup_Relationship_Notation__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Relationship_Notation__c</fullName>
    <description>If &apos;Is Lookup&apos; checked, then give the relationship field notation.</description>
    <inlineHelpText>Example : Put Id (field API name) as value for Account.Id
Note : Relationship field should be included in SOQL</inlineHelpText>
    <label>Lookup Relationship Notation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TPM_FieldsMapping__mdt/fields/TPM_FromFieldApi__c.field-meta.xml
<CustomField>
    <fullName>TPM_FromFieldApi__c</fullName>
    <label>From Field Api</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TPM_FieldsMapping__mdt/fields/TPM_IsLookup__c.field-meta.xml
<CustomField>
    <fullName>TPM_IsLookup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Assign SF_IDs for these fields</description>
    <label>Is Lookup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TPM_FieldsMapping__mdt/fields/TPM_ToFieldApi__c.field-meta.xml
<CustomField>
    <fullName>TPM_ToFieldApi__c</fullName>
    <label>To Field Api</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/TPM_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>LTA</fullName>
    </customValue>
    <customValue>
        <fullName>EDLP</fullName>
    </customValue>
    <customValue>
        <fullName>Short Term Event</fullName>
    </customValue>
    <customValue>
        <fullName>Other Programs</fullName>
    </customValue>
    <customValue>
        <fullName>Display Shipper</fullName>
    </customValue>
    <customValue>
        <fullName>Volume Push</fullName>
    </customValue>
    <customValue>
        <fullName>Logistic Discount</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor Discounts</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Price Reduction</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Price Reduction - Extra OI</fullName>
    </customValue>
    <customValue>
        <fullName>LTA - OI Extra</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Discounts</fullName>
    </customValue>
    <customValue>
        <fullName>Placement Fees</fullName>
    </customValue>
    <customValue>
        <fullName>Short Term Allowance</fullName>
    </customValue>
    <customValue>
        <fullName>Data / Market Research</fullName>
    </customValue>
    <customValue>
        <fullName>Displays and Fixtures</fullName>
    </customValue>
    <customValue>
        <fullName>In-Store Merchandising Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Other Sales Deductions</fullName>
    </customValue>
    <customValue>
        <fullName>Shopper Marketing Agency</fullName>
    </customValue>
    <customValue>
        <fullName>Shopper Marketing Execution</fullName>
    </customValue>
    <customValue>
        <fullName>100% TPR</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Media</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer &amp; Professionals</fullName>
    </customValue>
    <customValue>
        <fullName>LTA Fixed</fullName>
    </customValue>
    <customValue>
        <fullName>Stickering Fees</fullName>
    </customValue>
    <description>Type of Promotion and Tactics</description>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TPM_PromotionApprovalManager.cls
/******************************************************************************************************
@Name            TPM_PromotionApprovalManager
@testclass       TPM_PromotionCustomerPlanTriggerTest
@Author          PwC Team
@date            March 22, 2023
@description     methods for promotion record approvals/tactics creations and,
				 Handles business logic for approval records approvals routing
*******************************************************************************************************
Change History Story      Modified by               Date                          Desc

*******************************************************************************************************/
public inherited sharing class TPM_PromotionApprovalManager {
    
    /***************************************************************************************************
	@description	default private constructor
	****************************************************************************************************/
    @SuppressWarnings('PMD.EmptyStatementBlock')
    private TPM_PromotionApprovalManager() {

    }
    
    /*********************************************************************************
    @method          promotionApprovalHandler
	@param     	  	 promotionForApprovalMap
    @param     	  	 exceptionWrapperList
    @param           promoIdToPromotionTemplateIdMap
    @description     method to handle promotion and tactics approval creations
    **********************************************************************************/
    
    public static void promotionApprovalHandler(Map<Id, cgcloud__Promotion__c> promotionForApprovalMap, List<TPM_LoggerException.LogsWrapper> exceptionWrapperList, Map<String, String> promoIdToPromotionTemplateIdMap){
         
        //preparing a map of approval to be created for each promotion
        Map<Id, TPM_Approval__c> promotionIdToApprovalObjMap = prepareApprovalRecords(promotionForApprovalMap, promoIdToPromotionTemplateIdMap);
        
        //inserting and logging error(if any), for approval objects:
        if(!promotionIdToApprovalObjMap.isEmpty()){
            String objectName = TPM_ConstantsUtility.OBJECT_APPROVAL;
            createApprovalRecordsHandler(promotionIdToApprovalObjMap.values(), objectName, exceptionWrapperList);
        }
        
        //checking if the approval records are created then prepare records to be inserted for approval tactics
        if(TPM_Utils_Extension.isPromotionApprovalSuccess) {
            String objectName = TPM_ConstantsUtility.OBJECT_APPROVALTACTICS;
            createApprovalRecordsHandler(prepareApprovalTacticsRecords(promotionIdToApprovalObjMap), objectName, exceptionWrapperList);
        }
    }
    

     /********************************************************************************************************** 
	@methodname 	 prepareApprovalRecords
	@return          Map<Id, TPM_Approval__c>
	@param           promotionForApprovalMap
    @param           promoIdToPromotionTemplateIdMap
	@description	 create approval records when Phase changes from Planning to For Approval 
	***********************************************************************************************************/ 
    @SuppressWarnings('PMD.CyclomaticComplexity')
    public static Map<Id, TPM_Approval__c> prepareApprovalRecords(Map<Id, cgcloud__Promotion__c> promotionForApprovalMap, Map<String, String> promoIdToPromotionTemplateIdMap) {
        
        Map<Id, TPM_Approval__c> promoIdApprovalRecordMap = new Map<Id, TPM_Approval__c>();
        
        List<TPM_FieldsMapping__mdt> approvalFieldMappingRecordsList =  (List<TPM_FieldsMapping__mdt>)TPM_Utils_Extension.queryCustomMetadataRecords(TPM_ConstantsUtility.FIELDSMAPPING_METADATA_API, TPM_ConstantsUtility.FIELDSMAPPING_METADATA_FIELDSLIST, TPM_ConstantsUtility.FIELDSMAPPING_CRITERIAMAP_APPROVALPROMOTION);
        
        Map<Id, cgcloud__Promotion_Template__c> promoIdPromoTemplateRecordMap = fetchPromotionTemplateRecords(promoIdToPromotionTemplateIdMap);
        
		// recordid and submitter's manager or higher approverId assignment map       
        Map<Id, Id> promoIdToApproverIdMap = promotionApprovalRouting(promotionForApprovalMap);
                
        for(cgcloud__Promotion__c promoObj : promotionForApprovalMap.values()){
                          
            // initializing new approval recrod for promotion approval insert
            TPM_Approval__c newApprovalRecord = new TPM_Approval__c();
                        
            // iterating over field mapping for TPM_ApprovalPromotion
            for(TPM_FieldsMapping__mdt fieldMapRecord : approvalFieldMappingRecordsList){
                
                if(fieldMapRecord.TPM_IsLookup__c && String.isNotBlank(fieldMapRecord.Lookup_Relationship_Notation__c)){
                    
                    cgcloud__Promotion_Template__c promoTempObj = promoIdPromoTemplateRecordMap.get(promoObj.Id);
                    
                    if(fieldMapRecord.TPM_ToFieldApi__c.equalsIgnoreCase(TPM_ConstantsUtility.APPROVAL_FIELD_ISDISPLAY)){
                        
                        // is display marked TRUE on approval will depend on promotion template cgcloud__BOM_Handler__c if its value is ConsiderBOMs
                        Boolean isBOM = promoTempObj.get(fieldMapRecord.Lookup_Relationship_Notation__c) == TPM_ConstantsUtility.BOM_HANDLER_VAL_CONSIDER ? true : false;
                        newApprovalRecord.put(fieldMapRecord.TPM_ToFieldApi__c, isBOM);
                    } else {
                        newApprovalRecord.put(fieldMapRecord.TPM_ToFieldApi__c, promoTempObj.get(fieldMapRecord.Lookup_Relationship_Notation__c));
                    }
                    
                } else {
					newApprovalRecord.put(fieldMapRecord.TPM_ToFieldApi__c, promoObj.get(fieldMapRecord.TPM_FromFieldApi__c));
                    newApprovalRecord.put(TPM_ConstantsUtility.FIELD_RECORDTYPEID, Schema.SObjectType.TPM_Approval__c.getRecordTypeInfosByDeveloperName().get(TPM_ConstantsUtility.RECORDTYPE_PROMOTION).getRecordTypeId());
                } 
            } 
            
            // record owner assignment for approval
            if(promoIdToApproverIdMap.containsKey(promoObj.Id)) {
                newApprovalRecord.put('OwnerId', (Id) promoIdToApproverIdMap.get(promoObj.Id));
            } else {
                throw new TPM_PromotionApprovalException(System.Label.TPM_PromotionApproval_ApproverNotFoundError+''+promoObj.Id); 
            }

            // assign status approved when promotion current submitter is assigned as approver, auto-approved case
            if(promoObj.TPM_Promotion_Submitter__c == promoIdToApproverIdMap.get(promoObj.Id)){
                newApprovalRecord.put('TPM_Status__c', TPM_ConstantsUtility.PHASE_APPROVED);
            }
            
            promoIdApprovalRecordMap.put(promoObj.Id, newApprovalRecord);
        }
        
        return promoIdApprovalRecordMap;
    }
    
    /********************************************************************************************************** 
	@methodname 	 fetchPromotionTemplateRecords
	@return          Map<Id, cgcloud__Promotion_Template__c>
	@param           promoIdToPromotionTemplateIdMap
	@description	 create approval records when Phase changes from Planning to For Approval 
	***********************************************************************************************************/ 
    
    public static Map<Id, cgcloud__Promotion_Template__c> fetchPromotionTemplateRecords(Map<String, String> promoIdToPromotionTemplateIdMap) {

        // map of promotion id and template record
        Map<Id, cgcloud__Promotion_Template__c> promoIdPromoTemplateRecordMap = new Map<Id, cgcloud__Promotion_Template__c>();
                
        for(cgcloud__Promotion_Template__c promoTemplateObj : [SELECT Id, TPM_Type__c, cgcloud__BOM_Handler__c
                                             					FROM cgcloud__Promotion_Template__c 
                                             					WHERE Id IN : promoIdToPromotionTemplateIdMap.values()]){
                
            // method to get corr. key using value from map promoIdToPromotionTemplateIdMap
            String corrPromotionId = TPM_Utils_Extension.getKeyUsingValueFromMap(promoTemplateObj.Id, promoIdToPromotionTemplateIdMap);  

            if(!promoIdPromoTemplateRecordMap.containsKey(corrPromotionId)){
                promoIdPromoTemplateRecordMap.put(corrPromotionId, promoTemplateObj);
            }                                                                    
        }

        // returns map of promotion id and template records
        return promoIdPromoTemplateRecordMap;
    }
    
     /********************************************************************************************************** 
	@methodname 	 prepareApprovalTacticsRecords
	@return 	     List<TPM_Approval_Tactics__c>
	@param           promotionIdApprovalObjMap
	@description	 create approval tactics records when Phase changes from Planning to For Approval 
	***********************************************************************************************************/ 
    
    public static List<TPM_Approval_Tactics__c> prepareApprovalTacticsRecords(Map<Id, TPM_Approval__c> promotionIdApprovalObjMap){

        List<TPM_Approval_Tactics__c> tacticApprovalRecordList = new List<TPM_Approval_Tactics__c>();
        
        List<TPM_FieldsMapping__mdt> approvalTacticsFieldMappingRecordsList =  (List<TPM_FieldsMapping__mdt>)TPM_Utils_Extension.queryCustomMetadataRecords(TPM_ConstantsUtility.FIELDSMAPPING_METADATA_API, TPM_ConstantsUtility.FIELDSMAPPING_METADATA_FIELDSLIST, TPM_ConstantsUtility.FIELDSMAPPING_CRITERIAMAP_APPROVALTACTICS);
                
        for(cgcloud__Tactic__c tacticObj : [SELECT Id, cgcloud__Tactic_Type__c, 
                              					cgcloud__Compensation_Model__c, TPM_Volume_Basis__c, 
                              					cgcloud__Plan_Spend__c, cgcloud__Payment_Method__c, 
                              					cgcloud__Instore_Date_From__c, 
                              					cgcloud__Instore_Date_Thru__c, 
                              					cgcloud__Shipment_Date_From__c, 
                              					cgcloud__Shipment_Date_Thru__c,
                              					cgcloud__To_Date_Paid_Amount__c, 
                              					cgcloud__Promotion_Phase__c, cgcloud__Promotion__c,
                              					cgcloud__Pending_Amount__c, cgcloud__Included__c, 
                              					TPM_Redemption_Pct__c, TPM_Depth_of_Deal__c,
                              					cgcloud__Comment__c,TPM_Payment_Info__c  
                            				FROM cgcloud__Tactic__c
                            				WHERE cgcloud__Promotion__c IN : promotionIdApprovalObjMap.keySet()]) {
                                                                  
            // initializing new approval recrod for promotion approval insert
            TPM_Approval_Tactics__c newApprovalTacticsRecord = new TPM_Approval_Tactics__c();
            
            // iterating over field mapping for TPM_ApprovalTactic
            for(TPM_FieldsMapping__mdt fieldMapRecord : approvalTacticsFieldMappingRecordsList){

                if(String.isNotBlank(fieldMapRecord.TPM_ToFieldApi__c)){
					newApprovalTacticsRecord.put(fieldMapRecord.TPM_ToFieldApi__c, tacticObj.get(fieldMapRecord.TPM_FromFieldApi__c));
                } 
            } 
                                                          
            newApprovalTacticsRecord.put(TPM_ConstantsUtility.APPROVALTACTIC_FIELD_APPROVAL, promotionIdApprovalObjMap.get((String)tacticObj.get('cgcloud__Promotion__c')).Id);

            tacticApprovalRecordList.add(newApprovalTacticsRecord);
        }
        return tacticApprovalRecordList;
    }
    
    /*********************************************************************************
    @method          createApprovalRecordsHandler
	@param     	  	 recordsToInsert
	@param     	  	 objectName
    @param     	  	 exceptionWrapperList
    @description     method to insert the received approval objects(approval, approval tactics) 
    **********************************************************************************/
    
    public static void createApprovalRecordsHandler(List<sObject> recordsToInsert, String objectName, List<TPM_LoggerException.LogsWrapper> exceptionWrapperList){
                
        //inserting the received list of sobjects:
        Database.SaveResult[] saveResultList = Database.insert(recordsToInsert,false); 
        Integer index = 0;
                
        for (Database.SaveResult saveResultListObj : saveResultList) {
                        
            if(!saveResultListObj.isSuccess()){
                // preparing logger records to record failures                
                //checking the type of sobject passed to fetch the particular id to be logged as guid in the logger object in case of any error is encountered:
                // to detect approval object insertion failed and log error
                if(objectName == TPM_ConstantsUtility.OBJECT_APPROVAL){
                    List<TPM_Approval__c> approvalList = (List<TPM_Approval__c>)recordsToInsert;
                    TPM_Utils.LogParamWrapper loggerObj = TPM_Utils.createLogParamWrapper(saveResultListObj.getErrors(),
                                                                                          TPM_ConstantsUtility.TRIGGER_PROMOTION_HELPER,
                                                                                          approvalList[index].TPM_Promotion__c);
                    
                    exceptionWrapperList.add(TPM_Utils.prepareBatchLogger(loggerObj));
                    
                } 
                // to detect approval tactic object insertion failed and log error
                else if(objectName == TPM_ConstantsUtility.OBJECT_APPROVALTACTICS){
                    List<TPM_Approval_Tactics__c> approvalTacticList = (List<TPM_Approval_Tactics__c>)recordsToInsert;
                    TPM_Utils.LogParamWrapper loggerObj = TPM_Utils.createLogParamWrapper(saveResultListObj.getErrors(),
                                                                                          TPM_ConstantsUtility.TRIGGER_PROMOTION_HELPER,
                                                                                          approvalTacticList[index].TPM_Approval__c);
                    
                    exceptionWrapperList.add(TPM_Utils.prepareBatchLogger(loggerObj));
                }
                
            } else {
                if(objectName == TPM_ConstantsUtility.OBJECT_APPROVAL){
                    //marking flag to true in case approvals get created, so that approval tactics records can be prepared and inserted:
                    TPM_Utils_Extension.isPromotionApprovalSuccess = true;
                }
            }
            index++;
        }
        
    }
    
     /*********************************************************************************
    @method          promotionApprovalRouting
	@return          Map<Id, Id>
	@param     	  	 promotionForApprovalIdMap
    @description     method handles promotion approval routing 
    **********************************************************************************/
    
    public static Map<Id, Id> promotionApprovalRouting(Map<Id, cgcloud__Promotion__c> promotionForApprovalIdMap) {

        // map to return promotionid as key and user id as value for approver assignment
        Map<Id, Id> promotionIdToApproverIdMap = new Map<Id, Id>();
                
        // Map contains 'salesorg-approvallevel' as key and approval amount threshold stored as value in custom mapping metadata records
        Map<String, String> approverLvlToApprovalThresholdMap = TPM_PromotionApprovalUtils.fetchApproverLevelDataMapping();

        // collect all the unique submitter ids from the records List 
        Set<Id> recordSubmitterIdSet = new Set<Id>();
        
        for(cgcloud__Promotion__c promoObj : promotionForApprovalIdMap.values()){

            recordSubmitterIdSet.add(promoObj.TPM_Promotion_Submitter__c);
        }
		        
        // Query for all the users who are the record submitter
        Map<Id, User> promoSubmitterUserRecordMap = TPM_PromotionApprovalUtils.fetchRecordSubmitterUserRecords(recordSubmitterIdSet);
        
        for(String promoId : promotionForApprovalIdMap.keySet()) {
                        
            Boolean isAutoApprovalChecked = false;
            
            cgcloud__Promotion__c promotionRecord = promotionForApprovalIdMap.get(promoId);

            // Any promotion spend that is above $20,000,000 should be routed to Label.TPM_PromotionApproval_TopApproverName
            if(TPM_PromotionApprovalUtils.assignTopApprover(promotionRecord, promotionIdToApproverIdMap)){
                continue;
            }

            // check if record submitter has approval threshold to approve itself
            isAutoApprovalChecked = TPM_PromotionApprovalUtils.promotionAutoApproval(promoSubmitterUserRecordMap.get(promotionRecord.TPM_Promotion_Submitter__c), promotionRecord, approverLvlToApprovalThresholdMap, promotionIdToApproverIdMap);
                        
            if(!isAutoApprovalChecked) {
                
                // get submitter's manager or higher for approval assignment
        		// record submitter as key and manager as value
                TPM_PromotionApprovalUtils.fetchManagerForRecordApproval(promotionRecord, promoSubmitterUserRecordMap.get(promotionRecord.TPM_Promotion_Submitter__c), approverLvlToApprovalThresholdMap, promotionIdToApproverIdMap);                
            }            
        }

        return promotionIdToApproverIdMap;
    }
	
    /*******************************************************************************************************
    * @Name          TPM_PromotionApprovalException
    * @Author        PwC Team
    * @date          17 Apr, 2023
    * @description   Exception Class to throw Custom Exceptions
    *******************************************************************************************************
    Change History Story      Modified by               Date                          Desc

    *******************************************************************************************************/
    public class TPM_PromotionApprovalException extends Exception {}

}