force-app/main/default/objects/cgcloud__Tactic__c/fields/cgcloud__Compensation_Model__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Compensation_Model__c</fullName>
    <description>Which compensation model should be used for a tactic</description>
    <inlineHelpText>Rule to calculate promotion spend.</inlineHelpText>
    <label>Compensation Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LumpSum</fullName>
                <default>true</default>
                <label>LumpSum</label>
            </value>
            <value>
                <fullName>WeeklyLumpSum</fullName>
            </value>
            <value>
                <fullName>PerCase</fullName>
                <label>PerPack</label>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Tactic__c/fields/cgcloud__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Payment_Method__c</fullName>
    <description>Which payment method should be used for a tactic</description>
    <label>Claim Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deduction</fullName>
                <default>true</default>
                <label>Deduction</label>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>OnInvoice</fullName>
            </value>
            <value>
                <fullName>OffInvoice</fullName>
            </value>
            <value>
                <fullName>OI</fullName>
            </value>
            <value>
                <fullName>Billback/Retrospective</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_ZCodeDefinition__mdt/TPM_ZCodeDefinition__mdt.object-meta.xml
<CustomObject>
    <description>ZCode Pricing Condition Definition</description>
    <label>ZCode Pricing Condition Definition</label>
    <pluralLabel>ZCode Pricing Condition Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/TPM_ZCodeDefinition__mdt/fields/TPM_PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>TPM_PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deduction</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>OnInvoice</fullName>
            </value>
            <value>
                <fullName>OffInvoice</fullName>
            </value>
            <value>
                <fullName>OI</fullName>
            </value>
            <value>
                <fullName>Billback/Retrospective</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_ZCodeDefinition__mdt/fields/TPM_PromotionType__c.field-meta.xml
<CustomField>
    <fullName>TPM_PromotionType__c</fullName>
    <label>Promotion Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Display Shipper</fullName>
            </value>
            <value>
                <fullName>EDLP</fullName>
            </value>
            <value>
                <fullName>LTA</fullName>
            </value>
            <value>
                <fullName>Short Term Event</fullName>
            </value>
            <value>
                <fullName>Other Programs</fullName>
            </value>
            <value>
                <fullName>Volume Push</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_ZCodeDefinition__mdt/fields/TPM_RateBasis__c.field-meta.xml
<CustomField>
    <fullName>TPM_RateBasis__c</fullName>
    <label>Rate Basis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LumpSum</fullName>
            </value>
            <value>
                <fullName>WeeklyLumpSum</fullName>
            </value>
            <value>
                <fullName>PerCase</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_ZCodeDefinition__mdt/fields/TPM_SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>TPM_SalesOrg__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US01</fullName>
            </value>
            <value>
                <fullName>IT01</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_ZCodeDefinition__mdt/fields/TPM_TacticType__c.field-meta.xml
<CustomField>
    <fullName>TPM_TacticType__c</fullName>
    <label>Tactic Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Logistic Discount</fullName>
            </value>
            <value>
                <fullName>Distributor Discounts</fullName>
            </value>
            <value>
                <fullName>Consumer Price Reduction</fullName>
            </value>
            <value>
                <fullName>Consumer Price Reduction - Extra OI</fullName>
            </value>
            <value>
                <fullName>LTA</fullName>
            </value>
            <value>
                <fullName>LTA - OI Extra</fullName>
            </value>
            <value>
                <fullName>Display Shipper</fullName>
            </value>
            <value>
                <fullName>Cash Discounts</fullName>
            </value>
            <value>
                <fullName>EDLP</fullName>
            </value>
            <value>
                <fullName>Placement Fees</fullName>
            </value>
            <value>
                <fullName>Short Term Allowance</fullName>
            </value>
            <value>
                <fullName>Data / Market Research</fullName>
            </value>
            <value>
                <fullName>Displays and Fixtures</fullName>
            </value>
            <value>
                <fullName>In-Store Merchandising Labor</fullName>
            </value>
            <value>
                <fullName>Other Sales Deductions</fullName>
            </value>
            <value>
                <fullName>Shopper Marketing Agency</fullName>
            </value>
            <value>
                <fullName>Shopper Marketing Execution</fullName>
            </value>
            <value>
                <fullName>100% TPR</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Influencer &amp; Professionals</fullName>
            </value>
            <value>
                <fullName>LTA Fixed</fullName>
            </value>
            <value>
                <fullName>Stickering Fees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TPM_TacticConditionUtils.cls
/******************************************************************************************************
* @Name         : TPM_TacticConditionUtils
* @Test Class   : 
* @author       : PwC Team
* @date         : April 3, 2023
* @description  : 
*******************************************************************************************************
Change History Story      Modified by               Date                          Desc

*******************************************************************************************************/

public inherited sharing class TPM_TacticConditionUtils {
    
    // To fetch tactic price reduction record type id. 
    public static final Id TACTIC_PRICERED_RTID = Schema.SObjectType.cgcloud__Tactic__c
        										  .getRecordTypeInfosByDeveloperName()
        										  .get(TPM_ConstantsUtility.PRICE_REDUCTION_RT).getRecordTypeId();
    
    
    /*************************************************************************************
	* @method         : fetchMatchingZMetadataAPI
	* @param            tacticId
	* @param            tacticDataMap
	* @param            zCodesMap
    * @return           String
	* @description    : 
	**************************************************************************************/
    public static String fetchMatchingZMetadataAPI(Id tacticId, Map<Id,cgcloud__Tactic__c> tacticDataMap, Map<String, TPM_ZCodeDefinition__mdt> zCodesMap){
        
        String zCodeAPIName = '';
        for(String codeMDTAPIName : zCodesMap.keySet()){
            Boolean isTacticType = isSameMatch(zCodesMap.get(codeMDTAPIName).TPM_TacticType__c, tacticDataMap.get(tacticId).cgcloud__Tactic_Template__r.TPM_Type__c);
            Boolean isPaymentMethod = isSameMatch(zCodesMap.get(codeMDTAPIName).TPM_PaymentMethod__c, tacticDataMap.get(tacticId).cgcloud__Payment_Method__c);
            Boolean isSalesOrg = isSameMatch(zCodesMap.get(codeMDTAPIName).TPM_PromotionType__c, tacticDataMap.get(tacticId).cgcloud__Promotion__r.cgcloud__Promotion_Template__r.TPM_Type__c);
            Boolean isPromotionType = isSameMatch(zCodesMap.get(codeMDTAPIName).TPM_RateBasis__c, tacticDataMap.get(tacticId).cgcloud__Compensation_Model__c);
            Boolean isRateBasis = isSameMatch(zCodesMap.get(codeMDTAPIName).TPM_SalesOrg__c, tacticDataMap.get(tacticId).cgcloud__Sales_Org__c);
            
            if(isSalesOrg && isRateBasis && isPromotionType && isTacticType && isPaymentMethod){
                zCodeAPIName = codeMDTAPIName;
                break;
            }
        }
        return zCodeAPIName;
    }
    
    
    /*************************************************************************************
	* @method         : isSameMatch
	* @param            valueLHS
	* @param            valueRHS
    * @return           Boolean
	* @description    : 
	**************************************************************************************/
    public static Boolean isSameMatch(String valueLHS, String valueRHS){
        return valueLHS == valueRHS;
    }
    
}