force-app/main/default/objects/Account/fields/TPM_Hierarchy_Level__c.field-meta.xml
<CustomField>
    <fullName>TPM_Hierarchy_Level__c</fullName>
    <description>The level of the customer hierarchy in which this Account record lives</description>
    <label>Hierarchy Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Customer_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TPM_Planning_Mode__c.field-meta.xml
<CustomField>
    <fullName>TPM_Planning_Mode__c</fullName>
    <description>The planning mode of the Customer which controls the set of metrics displayed on the SVF</description>
    <label>Planning Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TPM_ProcessTPMCalculationChain__c.field-meta.xml
<CustomField>
    <fullName>TPM_ProcessTPMCalculationChain__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Executes the TPMCalculationChain batch.</description>
    <label>ProcessTPMCalculationChain</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/TPM_SAP_External_ID__c.field-meta.xml
<CustomField>
    <fullName>TPM_SAP_External_ID__c</fullName>
    <description>The External ID of the Account from integration</description>
    <externalId>true</externalId>
    <label>SAP External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/TPM_SAP_Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>TPM_SAP_Sales_Org__c</fullName>
    <description>The Sales Org of the Account from integration</description>
    <label>SAP Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>cgcloud__Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Account_Template__c/cgcloud__Account_Template__c.object-meta.xml
<CustomObject>
    <description>holds the details of the account template object to be used for accounts.</description>
    <label>Customer Template</label>
    <nameField>
        <label>Customer Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Account_Template__c/fields/TPM_CustTemp_PlanMode__c.field-meta.xml
<CustomField>
    <fullName>TPM_CustTemp_PlanMode__c</fullName>
    <defaultValue>&quot;General&quot;</defaultValue>
    <description>Describes the planning mode of the account defined at Account creation.</description>
    <label>Planning Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/cgcloud__Sales_Org.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US01</fullName>
    </customValue>
    <customValue>
        <fullName>IT01</fullName>
    </customValue>
    <customValue>
        <fullName>US08</fullName>
        <isActive>false</isActive>
        <label>US08</label>
    </customValue>
    <customValue>
        <fullName>US09</fullName>
        <isActive>false</isActive>
        <label>US09</label>
    </customValue>
    <customValue>
        <fullName>IT02</fullName>
        <isActive>false</isActive>
        <label>IT02</label>
    </customValue>
    <customValue>
        <fullName>0000</fullName>
        <isActive>false</isActive>
        <label>0000</label>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
        <isActive>false</isActive>
        <label>0003</label>
    </customValue>
    <customValue>
        <fullName>0002</fullName>
        <isActive>false</isActive>
        <label>0002</label>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
        <isActive>false</isActive>
        <label>0001</label>
    </customValue>
    <description>Sales Org value</description>
    <masterLabel>Sales Org</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TPM_Customer_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Total Sales Org</fullName>
    </customValue>
    <customValue>
        <fullName>SuperGroup</fullName>
    </customValue>
    <customValue>
        <fullName>Group</fullName>
    </customValue>
    <customValue>
        <fullName>Managed Account</fullName>
    </customValue>
    <customValue>
        <fullName>Sold-To</fullName>
    </customValue>
    <description>Levels of the customer</description>
    <masterLabel>Customer Level</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TPM_IT01CalculationChainQueueTest.cls
/*******************************************************************************************************
* @Name         : TPM_IT01CalculationChainQueueTest
* @author       : PwC Team
* @date         : April 11, 2023
* @description  : Test class for Queue - 'TPM_IT01CalculationChainQueue'
*******************************************************************************************************
Change History Story      Modified by               Date                          Desc

*******************************************************************************************************/
@isTest
public class TPM_IT01CalculationChainQueueTest {
    
    static String assertStr = 'Queue could not execute';
    
    /*********************************************************
    * @method         : createCustomerTemplate
    * @description    : To create customer template test data 
    **********************************************************/
    static void createCustomerTemplate() {
        
        String customerStr = 'Customer'; 
        String it01Str = 'IT01';
        String accountTemplateStr = 'cgcloud__Account_Template__c';
        
        // Create Customer Template records.
        cgcloud__Account_Template__c accountTemplateBasic = new cgcloud__Account_Template__c(Name = 'Basic_IT01', 
                                                                                             RecordTypeId = TPM_TestDataUtility.fetchRecordTypeId(customerStr, accountTemplateStr), 
                                                                                             cgcloud__Sales_Org__c = it01Str, 
                                                                                             cgcloud__Description_Language_1__c = 'Basic_IT01', 
                                                                                             cgcloud__Active__c = True, 
                                                                                             cgcloud__Initial_Roles__c = 'customer;payer', 
                                                                                             cgcloud__Available_Product_Level__c = 'SubCategory;Brand;Flavor;Package', 
                                                                                             TPM_CustTemp_PlanMode__c = 'Basic');
        insert accountTemplateBasic;
        
        // Create Customer Template records.
        cgcloud__Account_Template__c accountTemplateInter = new cgcloud__Account_Template__c(Name = 'Intermediate_IT01', 
                                                                                             RecordTypeId = TPM_TestDataUtility.fetchRecordTypeId(customerStr, accountTemplateStr), 
                                                                                             cgcloud__Sales_Org__c = it01Str, 
                                                                                             cgcloud__Description_Language_1__c = 'Intermediate_IT01', 
                                                                                             cgcloud__Active__c = True, 
                                                                                             cgcloud__Initial_Roles__c = 'customer;payer', 
                                                                                             cgcloud__Available_Product_Level__c = 'SubCategory;Brand;Flavor;Package', 
                                                                                             TPM_CustTemp_PlanMode__c = 'Intermediate');
        insert accountTemplateInter;      
    }
    
    /*********************************************************
    * @method         : createAccount
    * @description    : To create customer test data 
    **********************************************************/
    static void createAccount(){
        
        String customerStr = 'Customer'; 
        String it01Str = 'IT01';
        String accountStr = 'Account';
        String managedAccount ='Managed Account';
        
        cgcloud__Account_Template__c accountTemplateBasic = [SELECT Id,
                                                             		Name
                                                             FROM   cgcloud__Account_Template__c
                                                             WHERE  Name = 'Basic_IT01'];
        
        cgcloud__Account_Template__c accountTemplateInter = [SELECT Id,
                                                             		Name
                                                             FROM   cgcloud__Account_Template__c
                                                             WHERE  Name = 'Intermediate_IT01'];
        // Create account record.
        Account accountManagedObjOne = new Account(Name = 'TDC-1 Managed', 
                                                   RecordTypeId = TPM_TestDataUtility.fetchRecordTypeId(customerStr, accountStr), 
                                                   cgcloud__Account_Number__c = 'TDC1001', 
                                                   TPM_Hierarchy_Level__c = managedAccount, 
                                                   TPM_SAP_Sales_Org__c = it01Str, 
                                                   TPM_Planning_Mode__c = 'Basic',
                                                   TPM_SAP_External_ID__c = 'TDC1001_IT01_TDC',
                                                   TPM_ProcessTPMCalculationChain__c = TRUE,
                                                   cgcloud__Account_Template__c = accountTemplateBasic.Id);
        insert accountManagedObjOne;
        
        // Create account record.
        Account accountManagedObjTwo = new Account(Name = 'TDC-2 Managed', 
                                                   RecordTypeId = TPM_TestDataUtility.fetchRecordTypeId(customerStr, accountStr), 
                                                   cgcloud__Account_Number__c = 'TDC2002', 
                                                   TPM_Hierarchy_Level__c = managedAccount, 
                                                   TPM_SAP_Sales_Org__c = it01Str, 
                                                   TPM_Planning_Mode__c = 'Intermediate',
                                                   TPM_SAP_External_ID__c = 'TDC2002_IT01_TDC',
                                                   TPM_ProcessTPMCalculationChain__c = TRUE,
                                                   cgcloud__Account_Template__c = accountTemplateInter.Id);
        insert accountManagedObjTwo;
    }
    
    /*******************************************
    * @method         : setup
    * @description    : To create test data 
    ********************************************/
    @testSetup
    static void setup() {
        
        // Create Admin User.
        User adminUser = TPM_TestDataUtility.createTestUser(TPM_TestDataUtility.getProfileId('System Administrator'),
                                                            'testTPMAdminFName',
                                                            'testTPMAdminLName');

        adminUser.Email = 'tpmadminuser0001@invalidtpm.com';
        insert adminUser;

        System.runAs(adminUser) {    
            
            // Call createCustomerTemplate to create Template test data.
            createCustomerTemplate();
            
            // Call createAccount to create Account test data.
            createAccount();  
        }
    }
    
    /********************************************************************
    * @method         : it01CalculationChainQueue
    * @description    : To test IT01 Nightly Queue Class 
    *********************************************************************/
    @isTest static void it01CalculationChainQueue(){
        
        // Instantiate the Queue.
        TPM_IT01CalculationChainQueue  it01CalculationChainObj = new TPM_IT01CalculationChainQueue();

        test.startTest();
        
        // Execute the Queue.
		Test.setMock(HttpCalloutMock.class, new TPM_HttpMockGenerator());
        Id jobId = System.enqueueJob(it01CalculationChainObj);
		System.assertNotEquals(null, jobId, assertStr);
        test.stopTest();
    }

}