force-app/main/default/objects/Account/fields/TPM_SAP_Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>TPM_SAP_Sales_Org__c</fullName>
    <description>The Sales Org of the Account from integration</description>
    <label>SAP Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>cgcloud__Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/TPM_SAP_Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>TPM_SAP_Sales_Org__c</fullName>
    <description>Sales Org ID of the Product populated by integration</description>
    <label>SAP Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>cgcloud__Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/TPM_Logger__c.object-meta.xml
<CustomObject>
    <label>Logger</label>
    <nameField>
        <displayFormat>DUR-{000000}</displayFormat>
        <label>Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logger</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_ClassName__c.field-meta.xml
<CustomField>
    <fullName>TPM_ClassName__c</fullName>
    <description>Holds exception/error thrown apex class name.</description>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>TPM_ExceptionMessage__c</fullName>
    <description>Holds exception/error message.</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_FlowName__c.field-meta.xml
<CustomField>
    <fullName>TPM_FlowName__c</fullName>
    <description>Holds Business flow name.</description>
    <label>Flow Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_LogLevel__c.field-meta.xml
<CustomField>
    <fullName>TPM_LogLevel__c</fullName>
    <description>Hold logging level for tracking.</description>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fatal</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_MethodName__c.field-meta.xml
<CustomField>
    <fullName>TPM_MethodName__c</fullName>
    <description>Holds exception/error thrown Apex class Method/ (LWC) JS Function name.</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TPM_Logger__c/fields/TPM_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>TPM_StackTrace__c</fullName>
    <description>Use this to record complete error message.</description>
    <label>StackTrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/cgcloud__Sales_Org.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US01</fullName>
    </customValue>
    <customValue>
        <fullName>IT01</fullName>
    </customValue>
    <customValue>
        <fullName>US08</fullName>
        <isActive>false</isActive>
        <label>US08</label>
    </customValue>
    <customValue>
        <fullName>US09</fullName>
        <isActive>false</isActive>
        <label>US09</label>
    </customValue>
    <customValue>
        <fullName>IT02</fullName>
        <isActive>false</isActive>
        <label>IT02</label>
    </customValue>
    <customValue>
        <fullName>0000</fullName>
        <isActive>false</isActive>
        <label>0000</label>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
        <isActive>false</isActive>
        <label>0003</label>
    </customValue>
    <customValue>
        <fullName>0002</fullName>
        <isActive>false</isActive>
        <label>0002</label>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
        <isActive>false</isActive>
        <label>0001</label>
    </customValue>
    <description>Sales Org value</description>
    <masterLabel>Sales Org</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TPM_LoggerExceptionTest.cls
/******************************************************************************************************
* @Name         : TPM_LoggerExceptionTest
* @Author       : PwC Team
* @date         : December 23, 2022
* @description  : TPM_LoggerException class Test class
******************************************************************************************************
Change History Story      Modified by               Date                          Desc

*******************************************************************************************************/
@isTest
public class TPM_LoggerExceptionTest {
    public static final string EXP_MSG = 'Records found';
    
    /******************************************************************************************
    * @method			: exceptionErrorTest
    * @ param     		  none
    * @description    	: Method to test normal exceptions
    * 					  
    ******************************************************************************************/
    @isTest
    public static void exceptionErrorTest() {
        
        //Insert Accounts without required fields
        try {
            Account acc = new Account();
            insert acc;
        } catch (Exception exp) {
            TPM_LoggerException.LogsWrapper wrap = new TPM_LoggerException.LogsWrapper();
            wrap.exceptionObj = exp;
            wrap.logLevel = 'Error';
            
            //Call the TPM_LoggerException class log method
            TPM_LoggerException.log(new List<TPM_LoggerException.LogsWrapper>{wrap});
        }
        List<TPM_Logger__c> loggerObjList = [SELECT	Id, 
                                             		Name,
                                             		TPM_LogLevel__c,
                                             		TPM_StackTrace__c
                                             FROM	TPM_Logger__c
                                             WHERE	TPM_LogLevel__c ='Error'];
        System.assertEquals(false, loggerObjList.isEmpty(),EXP_MSG);
    }
    
   /******************************************************************************************
    * @method			: databaseDMLErrorTest
    * @ param     		  none
    * @description    	: Method to test Database DML Exceptions  				  
    ******************************************************************************************/
    @isTest
    public static void databaseDMLErrorTest(){
        
        List<Account> accToCreateList = new List<Account>();
        TPM_LoggerException.LogsWrapper wrap = new TPM_LoggerException.LogsWrapper();
        
        //Insert Bulk Accounts without required fields
        for(Integer cnt = 1;cnt <= 200;cnt++){
            Account acc = new Account();
            accToCreateList.add(acc);
        }
        
        //Insert Bulk Accounts without required fields
        Database.SaveResult[] insertAccSRList = Database.insert(accToCreateList,false);
        
        //Iterate over the inserted records
        for(Database.SaveResult result : insertAccSRList) {
            if(!result.isSuccess()) {
                wrap.logLevel = 'Error';
                wrap.className = 'TestClass';
                wrap.methodName = 'testMethod';
                wrap.errors = result.getErrors();
            }
        }
        
        //Call the TPM_LoggerException class log method
        TPM_LoggerException.log(new List<TPM_LoggerException.LogsWrapper>{wrap});
        List<TPM_Logger__c> loggerObjList = [SELECT	Id, 
                                             		Name,
                                             		TPM_LogLevel__c,
                                             		TPM_StackTrace__c
                                             FROM	TPM_Logger__c
                                             WHERE	TPM_ClassName__c ='TestClass'
                                             AND 	TPM_MethodName__c ='testMethod'];
        System.assertEquals(false, loggerObjList.isEmpty(),EXP_MSG);
    }
    
    /******************************************************************************************
    * @method			: logErrorTest
    * @ param     		  none
    * @description    	: Method to test log run once method in loggerclass  				  
    ******************************************************************************************/
    @isTest
    public static void logErrorTest(){
        
         //Call the TPM_LoggerException class log method
        TPM_LoggerException.log(new List<TPM_LoggerException.LogsWrapper>{null});
        List<TPM_Logger__c> loggerObjList = [SELECT	Id, 
                                             		Name,
                                             		TPM_LogLevel__c,
                                             		TPM_FlowName__c,
                                             		TPM_StackTrace__c
                                             FROM	TPM_Logger__c
                                             WHERE	TPM_FlowName__c ='Logger Module'];
        System.assertEquals(false, loggerObjList.isEmpty(),EXP_MSG);
        
    }
    
	/******************************************************************************************
    * @method			: customErrorTest
    * @ param     		  none
    * @description    	: Method to test custom errors				  
    ******************************************************************************************/
    @isTest
    public static void customErrorTest(){
        List<Product2> createProdList = new List<Product2>();
        for(Integer cnt=1;cnt<=200;cnt++){
            Product2 prodObj = new Product2();
            prodObj.Name = 'Test Product'+' '+cnt;
            prodObj.TPM_SAP_Sales_Org__c = 'US09';
            prodObj.cgcloud__Consumer_Goods_External_Product_Id__c = 'CGPRID'+cnt;
            prodObj.cgcloud__Consumer_Goods_Product_Code__c = 'CGPRC'+cnt;
            prodObj.cgcloud__Description_1_Language_1__c = 'Test Product'+' '+cnt;
            prodObj.cgcloud__Product_Level__c = 'Product';
            prodObj.RecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('Product').getRecordTypeId();
            createProdList.add(prodObj);
        }
        
        //Insert the test data list of Product Records
        if(!createProdList.isEmpty()){
            Database.insert(createProdList,false);
        }
        
        TPM_LoggerException.LogsWrapper wrap = new TPM_LoggerException.LogsWrapper();
        wrap.logLevel = 'Error';
        wrap.errorMessage ='Custom Error Log Test';
        
        //Call the TPM_LoggerException class log method
        TPM_LoggerException.log(new List<TPM_LoggerException.LogsWrapper>{wrap});
        List<TPM_Logger__c> loggerObjList = [SELECT	Id, 
                                             		Name,
                                             		TPM_LogLevel__c,
                                             		TPM_FlowName__c,
                                             		TPM_ExceptionMessage__c,
                                             		TPM_StackTrace__c
                                             FROM	TPM_Logger__c
                                             WHERE	TPM_LogLevel__c ='Error'
                                             LIMIT 	1];
        System.assertEquals('Custom Error Log Test',loggerObjList[0].TPM_ExceptionMessage__c,'Exception Message'); 
    }
}