force-app/main/default/objects/Account/fields/TPM_Hierarchy_Level__c.field-meta.xml
<CustomField>
    <fullName>TPM_Hierarchy_Level__c</fullName>
    <description>The level of the customer hierarchy in which this Account record lives</description>
    <label>Hierarchy Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Customer_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TPM_Planning_Mode__c.field-meta.xml
<CustomField>
    <fullName>TPM_Planning_Mode__c</fullName>
    <description>The planning mode of the Customer which controls the set of metrics displayed on the SVF</description>
    <label>Planning Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TPM_SAP_Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>TPM_SAP_Sales_Org__c</fullName>
    <description>The Sales Org of the Account from integration</description>
    <label>SAP Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>cgcloud__Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TPM_Sector__c.field-meta.xml
<CustomField>
    <fullName>TPM_Sector__c</fullName>
    <description>Sector of the customer</description>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TPM_Segment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Segment__c</fullName>
    <description>Segment of the customer</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TPM_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Subsegment__c</fullName>
    <description>SubSegment of the customer</description>
    <label>Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Subsegment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Account_Plan__c/cgcloud__Account_Plan__c.object-meta.xml
<CustomObject>
    <description>Container for Account Data for one Planning Account, one Business Year and one or multiple Categories.</description>
    <label>Customer Business Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Account_Plan__c/fields/TPM_Sector__c.field-meta.xml
<CustomField>
    <fullName>TPM_Sector__c</fullName>
    <description>Sector of the customer</description>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Account_Plan__c/fields/TPM_Segment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Segment__c</fullName>
    <description>Segment of the customer</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Account_Plan__c/fields/TPM_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Subsegment__c</fullName>
    <description>SubSegment of the customer</description>
    <label>Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Subsegment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Business_Year__c/cgcloud__Business_Year__c.object-meta.xml
<CustomObject>
    <description>This object holds the attributes of the Business Year</description>
    <label>Business Year</label>
    <nameField>
        <displayFormat>BY-{000000}</displayFormat>
        <label>Business Year Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Promotion__c/cgcloud__Promotion__c.object-meta.xml
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <label>Advanced Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advanced Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Promotion__c/fields/TPM_Sector__c.field-meta.xml
<CustomField>
    <fullName>TPM_Sector__c</fullName>
    <description>Sector of the customer</description>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Promotion__c/fields/TPM_Segment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Segment__c</fullName>
    <description>Segment of the customer</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Promotion__c/fields/TPM_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Subsegment__c</fullName>
    <description>SubSegment of the customer</description>
    <label>Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Subsegment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Promotion_Template__c/cgcloud__Promotion_Template__c.object-meta.xml
<CustomObject>
    <description>Template for the creation of a promotion.</description>
    <label>Promotion Template</label>
    <nameField>
        <label>Promotion Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Promotion_Template__c/fields/TPM_Planning_Mode__c.field-meta.xml
<CustomField>
    <fullName>TPM_Planning_Mode__c</fullName>
    <label>Planning Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_Trigger_Conditions_Check__c/TPM_Trigger_Conditions_Check__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom settings can be used to check functional specific conditions</description>
    <label>TPM Trigger Conditions Check</label>
</CustomObject>

force-app/main/default/objects/TPM_Trigger_Config_Settings__c/TPM_Trigger_Config_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TPM_Trigger Config Settings</label>
</CustomObject>

force-app/main/default/objects/User/fields/TPM_Sector__c.field-meta.xml
<CustomField>
    <fullName>TPM_Sector__c</fullName>
    <description>Sector of the customer</description>
    <label>Sector</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/TPM_Segment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Segment__c</fullName>
    <description>Segment of the customer</description>
    <label>Segment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/TPM_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Subsegment__c</fullName>
    <description>SubSegment of the customer</description>
    <label>Subsegment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Subsegment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/cgcloud__Sales_Org.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US01</fullName>
    </customValue>
    <customValue>
        <fullName>IT01</fullName>
    </customValue>
    <customValue>
        <fullName>US08</fullName>
        <isActive>false</isActive>
        <label>US08</label>
    </customValue>
    <customValue>
        <fullName>US09</fullName>
        <isActive>false</isActive>
        <label>US09</label>
    </customValue>
    <customValue>
        <fullName>IT02</fullName>
        <isActive>false</isActive>
        <label>IT02</label>
    </customValue>
    <customValue>
        <fullName>0000</fullName>
        <isActive>false</isActive>
        <label>0000</label>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
        <isActive>false</isActive>
        <label>0003</label>
    </customValue>
    <customValue>
        <fullName>0002</fullName>
        <isActive>false</isActive>
        <label>0002</label>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
        <isActive>false</isActive>
        <label>0001</label>
    </customValue>
    <description>Sales Org value</description>
    <masterLabel>Sales Org</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TPM_Customer_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Total Sales Org</fullName>
    </customValue>
    <customValue>
        <fullName>SuperGroup</fullName>
    </customValue>
    <customValue>
        <fullName>Group</fullName>
    </customValue>
    <customValue>
        <fullName>Managed Account</fullName>
    </customValue>
    <customValue>
        <fullName>Sold-To</fullName>
    </customValue>
    <description>Levels of the customer</description>
    <masterLabel>Customer Level</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TPM_Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>ASIA</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>B2B</fullName>
    </customValue>
    <customValue>
        <fullName>Portable power</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <description>Sector of the customer</description>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TPM_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FOOD_DRUG</fullName>
    </customValue>
    <customValue>
        <fullName>TI</fullName>
    </customValue>
    <customValue>
        <fullName>DOA</fullName>
    </customValue>
    <customValue>
        <fullName>Russia</fullName>
    </customValue>
    <customValue>
        <fullName>NCE</fullName>
    </customValue>
    <customValue>
        <fullName>BNL</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>CLUB</fullName>
    </customValue>
    <customValue>
        <fullName>MEXICO</fullName>
    </customValue>
    <customValue>
        <fullName>BRAZIL</fullName>
    </customValue>
    <customValue>
        <fullName>LADEX</fullName>
    </customValue>
    <customValue>
        <fullName>CHINA</fullName>
    </customValue>
    <customValue>
        <fullName>AADO</fullName>
    </customValue>
    <customValue>
        <fullName>South Korea</fullName>
    </customValue>
    <customValue>
        <fullName>WALM_MASS</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon</fullName>
    </customValue>
    <customValue>
        <fullName>Portable power</fullName>
    </customValue>
    <customValue>
        <fullName>HOME_HW</fullName>
    </customValue>
    <customValue>
        <fullName>ALT</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>B2B America</fullName>
    </customValue>
    <customValue>
        <fullName>B2B International</fullName>
    </customValue>
    <customValue>
        <fullName>CHILE</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>UK&amp;I</fullName>
    </customValue>
    <description>Segment of the customer</description>
    <masterLabel>Segment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TPM_Subsegment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Australia/NewZealand</fullName>
    </customValue>
    <customValue>
        <fullName>BNL</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Central Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Club</fullName>
    </customValue>
    <customValue>
        <fullName>Costco</fullName>
    </customValue>
    <customValue>
        <fullName>DACH</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor Operation</fullName>
    </customValue>
    <customValue>
        <fullName>Drug</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai Hub</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Global OEM</fullName>
    </customValue>
    <customValue>
        <fullName>Home/Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>LA Comm Oth</fullName>
    </customValue>
    <customValue>
        <fullName>Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>OEM Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>P. AFTMKT AMERICAS</fullName>
    </customValue>
    <customValue>
        <fullName>P. AFTMKT ASIA</fullName>
    </customValue>
    <customValue>
        <fullName>P. AFTMKT EUROPE</fullName>
    </customValue>
    <customValue>
        <fullName>P. OEM ASIA</fullName>
    </customValue>
    <customValue>
        <fullName>P. OEM EUROPE</fullName>
    </customValue>
    <description>SubSegment of the customer</description>
    <masterLabel>Subsegment</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TPM_AccountTriggerTest.cls
/*******************************************************************************************************
* @Name         : TPM_AccountTriggerTest
* @author       : PwC Team
* @date         : March 7, 2023
* @description  : Test class for TPM_AccountTrigger
*******************************************************************************************************
Change History Story      Modified by               Date                          Desc

*******************************************************************************************************/
@isTest
public with sharing class TPM_AccountTriggerTest {
    
    static String assertStr = 'Exception message should not be empty';
    static String test ='Test';
    static String us ='NA';
    static String foodDrug ='FOOD_DRUG';
    static String drug ='Drug';
    
    /*********************************************************************************
	@description      create test data records
	**********************************************************************************/
    @testSetup
    static void setup() {
        String customerStr = 'Customer'; 
        String us01Str = 'US01';
        String accountStr = 'Account';
        String managedAccount ='Managed Account';
        
        //insert custom setting TPM_Trigger_Config_Settings__c
        List<TPM_Trigger_Config_Settings__c> triggerConfigSettingList = TPM_TestDataUtility.createTriggerConfigSetting();
        insert triggerConfigSettingList;
        
        //insert custom setting TPM_Trigger_Conditions_Check__c
        List<TPM_Trigger_Conditions_Check__c> triggerConditionCheckList = TPM_TestDataUtilityExtension.createTriggerConditionCheck();
        insert triggerConditionCheckList;
        
        // Create Business Admin User.
        User busAdminUser = TPM_TestDataUtility.createTestUser(TPM_TestDataUtility.getProfileId('Business Admin'),
                                                               'testTPMAdminFName',
                                                               'testTPMAdminLName');
        
        //Add email
        busAdminUser.Email = 'tpmadminuser008@invalidtpm.com';
        
        //Insert business admin user
        insert busAdminUser;
        
        // Create account record.
        Account accountTestTrigger = new Account(Name = 'TestTriggerAcc', 
                                                 RecordTypeId = TPM_TestDataUtility.fetchRecordTypeId(customerStr, accountStr), 
                                                 TPM_Hierarchy_Level__c = managedAccount, 
                                                 TPM_SAP_Sales_Org__c = us01Str, 
                                                 TPM_Planning_Mode__c = 'Basic');
        insert accountTestTrigger;
        
        // Create Admin User.
        User adminUser = TPM_TestDataUtility.createTestUser(TPM_TestDataUtility.getProfileId('System Administrator'),
                                                            'testTPMAdminFName',
                                                            'testTPMAdminLName');
        
        //Add email
        adminUser.Email = 'tpmadminuser008@invalidtpm.com';
        //Insert admin user
        insert adminUser;
        
        // Create Admin NewUser.
        User adminUserNew = TPM_TestDataUtility.createTestUser(TPM_TestDataUtility.getProfileId('System Administrator'),
                                                               'testTPMAdminNewFName',
                                                               'testTPMAdminNewLName');
        
        //Add email
        adminUserNew.Email = 'tpmadminusernew008@invalidtpm.com';
        //Insert admin new user
        insert adminUserNew;
        
        System.runAs(adminUser) {   
                        
            //insert supergroup
            Account totalSaslesOrgAcc = TPM_TestDataUtility.createAccountByHierarchy('Total Sales Org', null);
            insert totalSaslesOrgAcc;
            
            //insert supergroup
            Account superGroupAcc = TPM_TestDataUtility.createAccountByHierarchy('SuperGroup', totalSaslesOrgAcc.Id);
            insert superGroupAcc;
            
            //insert group
            Account groupAcc = TPM_TestDataUtility.createAccountByHierarchy('Group', superGroupAcc.Id);
            insert groupAcc;
            
            //insert Managed account
            Account managedAccountAcc = TPM_TestDataUtility.createAccountByHierarchy('Managed Account', GroupAcc.Id);
            insert managedAccountAcc;
            
            AccountTeamMember accTeamMemberObj1 = TPM_TestDataUtility.createAccountTeamMember(managedAccountAcc.Id, adminUser.Id);
            insert accTeamMemberObj1;
            
            AccountTeamMember accTeamMemberObj2 = TPM_TestDataUtility.createAccountTeamMember(managedAccountAcc.Id, adminUserNew.Id);
            insert accTeamMemberObj2;
            
            //Create Promotion template
            cgcloud__Promotion_Template__c promotionTemp = TPM_TestDataUtilityExtension.createPromotionTemplate();
            insert promotionTemp;
            
            //Create promotion
            cgcloud__Promotion__c promotionRec = TPM_TestDataUtilityExtension.createPromotion(managedAccountAcc.Id, promotionTemp.Id);
            insert promotionRec;
            
            //Create customer business plan
            cgcloud__Account_Plan__c busPlanRec = new cgcloud__Account_Plan__c(cgcloud__Account__c = managedAccountAcc.Id,
                                                                               cgcloud__Business_Year__c = 2023,
                                                                               cgcloud__Description_Language_1__c = test,
                                                                               cgcloud__Category_Labels_Language_1__c = test);
            insert busPlanRec;  
            
        }
    }
    
    /*********************************************************************************
	@description      Call the class to check validation for account update
	**********************************************************************************/
    @isTest
    public static void executeAccountTriggerUpdate(){
        
        //Fetch business admin users
        User busAdminUser = [SELECT Id 
                             FROM User 
                             WHERE Email = 'tpmadminuser008@invalidtpm.com' LIMIT 1];
        
        //Add Business Admin Permission set
        PermissionSet permission =[SELECT Id, 
                                   Name 
                                   FROM PermissionSet 
                                   WHERE Name = 'TPM_Business_Admin_Permission_Set'];
        PermissionSetAssignment permissionSetAssignment = new PermissionSetAssignment();
        permissionSetAssignment.PermissionSetId = permission.Id;
        permissionSetAssignment.AssigneeId = busAdminUser.Id;
        
        //Add this permission set to business admin user
        insert permissionSetAssignment;
        
        //Run as business admin user
        System.runAs(busAdminUser){
            System.Test.startTest();
            
            try{
                Account acc = [SELECT Id,
                               Name
                               FROM Account 
                               WHERE  Name = 'TestTriggerAcc' LIMIT 1];
                //try to update account and validation should be thrown
                acc.Name = 'UpdateTestTriggerAcc';
                update acc;
            }
            catch(Exception exp){
                System.Assert(String.isNotBlank(exp.getMessage()),assertStr);
            }
            System.Test.stopTest();
            
        }
        
        //Call other methods of trigger handler
        List<Sobject> sobectList = new List<Sobject>();
        Map<Id, SObject> newMapParam = new  Map<Id, SObject>();
        Map<Id, SObject> oldMapParam = new  Map<Id, SObject>();
        TPM_AccountTriggerHandler tpmTriggerHandler = new TPM_AccountTriggerHandler();
        tpmTriggerHandler.bulkBefore();
        tpmTriggerHandler.bulkAfter();
        tpmTriggerHandler.beforeInsert(sobectList);
        tpmTriggerHandler.afterInsert(newMapParam);
        tpmTriggerHandler.afterUpdate(newMapParam,oldMapParam);
        tpmTriggerHandler.afterDelete(oldMapParam);
        tpmTriggerHandler.afterUnDelete(sobectList);
        
        
    }
    
    /*********************************************************************************
	@description      Call the class to check validation for account delete
	**********************************************************************************/
    @isTest
    public static void executeAccountTriggerDelete(){
        
        //Fetch business admin user
        User busAdminUser = [SELECT Id 
                             FROM User 
                             WHERE Email = 'tpmadminuser008@invalidtpm.com' LIMIT 1];
        //Add Business Admin Permission set
        PermissionSet permission =[SELECT Id, Name FROM PermissionSet WHERE Name = 'TPM_Business_Admin_Permission_Set'];
        PermissionSetAssignment permissionSetAssignment = new PermissionSetAssignment();
        permissionSetAssignment.PermissionSetId = permission.Id;
        permissionSetAssignment.AssigneeId = busAdminUser.Id;
        
        //Add this permission set to business admin user
        insert permissionSetAssignment;
        
        //Run as business admin user
        System.runAs(busAdminUser){
            
            System.Test.startTest();
            try{
                
                Account acc = [SELECT Id,
                               Name
                               FROM Account 
                               WHERE Name = 'TestTriggerAcc' LIMIT 1];
                
                //try to Delete account and validation should be thrown
                Delete acc;
            }
            
            catch(Exception exp){
                
                System.Assert(String.isNotBlank(exp.getMessage()),assertStr);
                
            }
            System.Test.stopTest();
        }
        
    }
    
    /******************************************************************************************
    * @method			testAccountTeamHandlerMethod
    * @ return     		void
    * @param   		  
    * @description    	test method for account trigger handler
    ******************************************************************************************/
    @isTest
    public static void testAccountUpdateMethod() {
        
        Account managedAccount = [SELECT Id, Name, TPM_Hierarchy_Level__c, TPM_Sector__c, TPM_Segment__c, TPM_Subsegment__c FROM Account WHERE Name LIKE 'Test Customer%' AND TPM_Hierarchy_Level__c = 'Managed Account' LIMIT 1];
        managedAccount.TPM_Sector__c = us;
        managedAccount.TPM_Segment__c = foodDrug;
        managedAccount.TPM_Subsegment__c = drug;
        update managedAccount;
        
        // promotions verify field updates
        List<cgcloud__Promotion__c> promRec = [SELECT id,TPM_Sector__c,TPM_Segment__c,TPM_Subsegment__c from cgcloud__Promotion__c WHERE cgcloud__Anchor_Account__c = :managedAccount.Id];
        
        for(cgcloud__Promotion__c existingProm : promRec){
            
            System.assertEquals(us, existingProm.TPM_Sector__c, TPM_TestAutomationDataUtility.RECORDSDONTMATCH);
            System.assertEquals(foodDrug, existingProm.TPM_Segment__c, TPM_TestAutomationDataUtility.RECORDSDONTMATCH);
            System.assertEquals(drug, existingProm.TPM_Subsegment__c, TPM_TestAutomationDataUtility.RECORDSDONTMATCH);
        }
        
        
        // customer business plan verify field updates
        List<cgcloud__Account_Plan__c> busPlanRecord = [SELECT id,TPM_Sector__c,TPM_Segment__c,TPM_Subsegment__c from cgcloud__Account_Plan__c WHERE cgcloud__Account__c = :managedAccount.Id LIMIT 1];
        
        for(cgcloud__Account_Plan__c exisBusPlan : busPlanRecord){
            
            System.assertEquals(us, exisBusPlan.TPM_Sector__c, TPM_TestAutomationDataUtility.RECORDSDONTMATCH);
            System.assertEquals(foodDrug, exisBusPlan.TPM_Segment__c, TPM_TestAutomationDataUtility.RECORDSDONTMATCH);
            System.assertEquals(drug, exisBusPlan.TPM_Subsegment__c, TPM_TestAutomationDataUtility.RECORDSDONTMATCH);
        }
        
    }
    
    /******************************************************************************************
    * @method			testAccountUpdateErrors
    * @ return     		void
    * @param   		  
    * @description    	test method for account trigger handler
    ******************************************************************************************/
    @isTest
    public static void testAccountUpdateErrors() {
        
        Map<Id,Account> managedAccount = new Map<Id,Account>([SELECT Id, TPM_Sector__c, TPM_Segment__c, TPM_Subsegment__c FROM Account WHERE Name LIKE 'Test Customer%' AND TPM_Hierarchy_Level__c = 'Managed Account']);

        System.Test.startTest();
        try{
            TPM_AccountTriggerHelper.updateRelatedRecordsInfo(managedAccount,  Null);
        }catch(Exception excep){
            System.assert(excep.getMessage().contains('MISSING_ARGUMENT'));
        }
        System.Test.stopTest();
    }
    
}