force-app/main/default/objects/Account/fields/TPM_Sector__c.field-meta.xml
<CustomField>
    <fullName>TPM_Sector__c</fullName>
    <description>Sector of the customer</description>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TPM_Segment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Segment__c</fullName>
    <description>Segment of the customer</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TPM_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Subsegment__c</fullName>
    <description>SubSegment of the customer</description>
    <label>Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Subsegment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Account_Plan__c/cgcloud__Account_Plan__c.object-meta.xml
<CustomObject>
    <description>Container for Account Data for one Planning Account, one Business Year and one or multiple Categories.</description>
    <label>Customer Business Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Account_Plan__c/fields/TPM_Sector__c.field-meta.xml
<CustomField>
    <fullName>TPM_Sector__c</fullName>
    <description>Sector of the customer</description>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Account_Plan__c/fields/TPM_Segment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Segment__c</fullName>
    <description>Segment of the customer</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Account_Plan__c/fields/TPM_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Subsegment__c</fullName>
    <description>SubSegment of the customer</description>
    <label>Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Subsegment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Promotion__c/cgcloud__Promotion__c.object-meta.xml
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <label>Advanced Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advanced Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Promotion__c/fields/TPM_Sector__c.field-meta.xml
<CustomField>
    <fullName>TPM_Sector__c</fullName>
    <description>Sector of the customer</description>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Promotion__c/fields/TPM_Segment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Segment__c</fullName>
    <description>Segment of the customer</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Promotion__c/fields/TPM_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Subsegment__c</fullName>
    <description>SubSegment of the customer</description>
    <label>Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Subsegment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TPM_Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>ASIA</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>B2B</fullName>
    </customValue>
    <customValue>
        <fullName>Portable power</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <description>Sector of the customer</description>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TPM_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FOOD_DRUG</fullName>
    </customValue>
    <customValue>
        <fullName>TI</fullName>
    </customValue>
    <customValue>
        <fullName>DOA</fullName>
    </customValue>
    <customValue>
        <fullName>Russia</fullName>
    </customValue>
    <customValue>
        <fullName>NCE</fullName>
    </customValue>
    <customValue>
        <fullName>BNL</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>CLUB</fullName>
    </customValue>
    <customValue>
        <fullName>MEXICO</fullName>
    </customValue>
    <customValue>
        <fullName>BRAZIL</fullName>
    </customValue>
    <customValue>
        <fullName>LADEX</fullName>
    </customValue>
    <customValue>
        <fullName>CHINA</fullName>
    </customValue>
    <customValue>
        <fullName>AADO</fullName>
    </customValue>
    <customValue>
        <fullName>South Korea</fullName>
    </customValue>
    <customValue>
        <fullName>WALM_MASS</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon</fullName>
    </customValue>
    <customValue>
        <fullName>Portable power</fullName>
    </customValue>
    <customValue>
        <fullName>HOME_HW</fullName>
    </customValue>
    <customValue>
        <fullName>ALT</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>B2B America</fullName>
    </customValue>
    <customValue>
        <fullName>B2B International</fullName>
    </customValue>
    <customValue>
        <fullName>CHILE</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>UK&amp;I</fullName>
    </customValue>
    <description>Segment of the customer</description>
    <masterLabel>Segment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TPM_Subsegment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Australia/NewZealand</fullName>
    </customValue>
    <customValue>
        <fullName>BNL</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Central Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Club</fullName>
    </customValue>
    <customValue>
        <fullName>Costco</fullName>
    </customValue>
    <customValue>
        <fullName>DACH</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor Operation</fullName>
    </customValue>
    <customValue>
        <fullName>Drug</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai Hub</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Global OEM</fullName>
    </customValue>
    <customValue>
        <fullName>Home/Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>LA Comm Oth</fullName>
    </customValue>
    <customValue>
        <fullName>Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>OEM Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>P. AFTMKT AMERICAS</fullName>
    </customValue>
    <customValue>
        <fullName>P. AFTMKT ASIA</fullName>
    </customValue>
    <customValue>
        <fullName>P. AFTMKT EUROPE</fullName>
    </customValue>
    <customValue>
        <fullName>P. OEM ASIA</fullName>
    </customValue>
    <customValue>
        <fullName>P. OEM EUROPE</fullName>
    </customValue>
    <description>SubSegment of the customer</description>
    <masterLabel>Subsegment</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TPM_AccountTriggerHelper.cls
/******************************************************************************************************
@Name            TPM_AccountTriggerHelper
@testclass       TPM_AccountTriggerTest
@Author          PwC Team
@date            March 02, 2023
@description     Handles business logic for Account Trigger Handler 
*******************************************************************************************************
Change History Story      Modified by               Date                          Desc

*******************************************************************************************************/
public inherited sharing class TPM_AccountTriggerHelper {
    /***************************************************************************************************
	@description	default private constructor
	****************************************************************************************************/
    @SuppressWarnings('PMD.EmptyStatementBlock')
    private TPM_AccountTriggerHelper() { 
        
    }



    /********************************************************************************************************** 
	@methodname 	 preventModificationOfAccount
	@param           newMap
	@param           oldMap
	@description	 method handles the process to prevent updation of account records for Business Admin
	***********************************************************************************************************/  
    public static void preventModificationOfAccount(Map<Id, SObject> newMap, Map<Id, SObject> oldMap){
        
        //Map of Old Records
        Map<Id, Account> assortmentOldMap = (Map<Id, Account>)oldMap;
        
        //Loop new records and check if the values of the fields in fieldsets 
        //are changed and if changed by business admin throw error
        for(Account acc : (List<Account>)newMap.Values()){
            Account accOld = assortmentOldMap.get(acc.id);
           for(FieldSetMember fld : SObjectType.Account.FieldSets.TPM_Account.getFields()) {

            //Compare old and new values of fields in field set
               if(accOld.get(fld.getSObjectField()) != acc.get(fld.getSObjectField())){
                acc.addError(System.Label.TPM_Account_Error_Message);
               }
          }

        }


    }
        
    /********************************************************************************************************** 
	@methodname 	 preventDeletionOfAccount
	@param           oldMap
	@description	 method handles the process to prevent Deletion of Account records for Business Admin
	***********************************************************************************************************/  
    public static void preventDeletionOfAccount(Map<Id,SObject> oldMap){
        //Loop all records which are going to be deleted and avoid 
        //deletion of records for business admin

        for(Account acc : (List<Account>)oldMap.Values()){
           acc.addError(System.Label.TPM_Account_Error_Message_Delete);
       }
    }

    /*********************************************************************************************************
    @methodname   	updateAccountChildInfo
    @createdDate  	03/06/2023
    @param     	  	newMap
    @param     	  	oldMap
    @description  	handles accounts sector, segment, subsegment sync for promotions and svf
    *********************************************************************************************************/
    public static void updateRelatedRecordsInfo(Map<Id,SObject> newMap, Map<Id,SObject> oldMap) {

        List<TPM_LoggerException.LogsWrapper> exceptionWrapperList = new List<TPM_LoggerException.LogsWrapper>();
        
        // list of Sobject to update account's related child record updates
        List<SObject> childRecordsToUpdate = new List<SObject>();

        // to filter out account ids set to process for child records query
        Set<Id> accountsToConsiderIdSet = new Set<Id>();
        try{
            //typecasting oldMap to map of accounts by Id
            Map<Id, Account> oldAccountMap = (Map<Id, Account>)oldMap;

            for(Account accountObj : (List<Account>)newMap.values()) {
                if(accountObj.TPM_Sector__c != oldAccountMap.get(accountObj.Id).TPM_Sector__c 
                || accountObj.TPM_Segment__c != oldAccountMap.get(accountObj.Id).TPM_Segment__c
                || accountObj.TPM_Subsegment__c != oldAccountMap.get(accountObj.Id).TPM_Subsegment__c){

                    accountsToConsiderIdSet.add(accountObj.Id);
                }
            }
                
            for(Account accountObj : [SELECT Id, TPM_Sector__c, TPM_Segment__c, TPM_Subsegment__c,
                                        (SELECT Id, TPM_Sector__c, TPM_Segment__c, TPM_Subsegment__c 
                                            FROM cgcloud__Promotions__r),
                                        (SELECT Id, TPM_Sector__c, TPM_Segment__c, TPM_Subsegment__c 
                                            FROM cgcloud__Customer_Business_Plans__r)
                                        FROM Account WHERE Id IN: accountsToConsiderIdSet]){
            
                preparePromotionSVFFieldUpdate(accountObj, childRecordsToUpdate);
            }

            if(!childRecordsToUpdate.isEmpty()){
                updateAccountRelatedSobjectRecords(childRecordsToUpdate, exceptionWrapperList, TPM_ConstantsUtility.ACCOUNT_TRIGGER_HELPER);
            }
        }
        catch(Exception exp){
            TPM_LoggerException.LogsWrapper logWrapperObj = new TPM_LoggerException.LogsWrapper();
            logWrapperObj.exceptionObj = exp;
            logWrapperObj.logLevel = TPM_ConstantsUtility.FATAL;
            exceptionWrapperList.add(logWrapperObj);
            // Call the TPM_LoggerException class log method to save all the exception details during insert
            TPM_LoggerException.log(exceptionWrapperList);
        }

    }

    /********************************************************************************************************** 
    @methodname 	 preparePromotionSVFFieldUpdate
    @param           accountObj
    @param           childRecordsToUpdate
    @description	 method updates sector, segment, subsegment on promotions and svf
    ***********************************************************************************************************/ 
    //bypassing since this ruleset is not applicable because the target and destination instance is different: 
    @SuppressWarnings('PMD.IdempotentOperations')
    public static void preparePromotionSVFFieldUpdate(Account accountObj, List<SObject> childRecordsToUpdate){

        // promotion field update assigment
        for(cgcloud__Promotion__c promoObj :  accountObj.cgcloud__Promotions__r) {
            promoObj.TPM_Sector__c = accountObj.TPM_Sector__c;
            promoObj.TPM_Segment__c = accountObj.TPM_Segment__c;
            promoObj.TPM_Subsegment__c = accountObj.TPM_Subsegment__c;
            childRecordsToUpdate.add(promoObj);
        }

        // SVF field update assigment
        for(cgcloud__Account_Plan__c accountPlanObj :  accountObj.cgcloud__Customer_Business_Plans__r) {
            accountPlanObj.TPM_Sector__c = accountObj.TPM_Sector__c;
            accountPlanObj.TPM_Segment__c = accountObj.TPM_Segment__c;
            accountPlanObj.TPM_Subsegment__c = accountObj.TPM_Subsegment__c;
            childRecordsToUpdate.add(accountPlanObj);
        }
    }

    /********************************************************************************************************** 
    @methodname 	 updateAccountRelatedSobjectRecords
    @param           recordsToUpdateList
    @param           exceptionWrapperList
    @param           flowName
    @description	 method handles the process to share all new records related to customer with account team members 
    ***********************************************************************************************************/ 
    public static void updateAccountRelatedSobjectRecords(List<sObject> recordsToUpdateList, List<TPM_LoggerException.LogsWrapper> exceptionWrapperList, String flowName){

        // database operation for partial insert
        Database.SaveResult[] shareResults = Database.update(recordsToUpdateList, false);
        Integer index = 0;
        
        for(Database.SaveResult sResults : shareResults){
            if(!sResults.isSuccess()){

                // preparing logger records to record failures
                TPM_LoggerException.LogsWrapper logObj = new TPM_LoggerException.LogsWrapper();
                logObj.flow = flowName;
                logObj.logLevel = TPM_ConstantsUtility.ERROR;
                logObj.guid = (String)recordsToUpdateList[index].Id;
                logObj.errors = sResults.getErrors();
                exceptionWrapperList.add(logObj);
            }
            index++;
        }
    }
    
}