force-app/main/default/objects/Account/fields/TPM_Hierarchy_Level__c.field-meta.xml
<CustomField>
    <fullName>TPM_Hierarchy_Level__c</fullName>
    <description>The level of the customer hierarchy in which this Account record lives</description>
    <label>Hierarchy Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Customer_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TPM_Is_Assortment_Created__c.field-meta.xml
<CustomField>
    <fullName>TPM_Is_Assortment_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field identifies whether assortment has been created for the account.</description>
    <label>Is Assortment Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cgcloud__Account_Template__c/cgcloud__Account_Template__c.object-meta.xml
<CustomObject>
    <description>holds the details of the account template object to be used for accounts.</description>
    <label>Customer Template</label>
    <nameField>
        <label>Customer Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Product_Assortment_Template__c/cgcloud__Product_Assortment_Template__c.object-meta.xml
<CustomObject>
    <description>Template for product assortments. Controls the behaviour of the instances of this template, for example if a business partner must be specified (AccountMultiplicity). This table is sales organization dependent.</description>
    <label>Product Assortment Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Assortment Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/TPM_Customer_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Total Sales Org</fullName>
    </customValue>
    <customValue>
        <fullName>SuperGroup</fullName>
    </customValue>
    <customValue>
        <fullName>Group</fullName>
    </customValue>
    <customValue>
        <fullName>Managed Account</fullName>
    </customValue>
    <customValue>
        <fullName>Sold-To</fullName>
    </customValue>
    <description>Levels of the customer</description>
    <masterLabel>Customer Level</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TPM_AssortmentCreationBatchTest.cls
/*******************************************************************************************************
* @Name         : TPM_AssortmentCreationBatchTest
* @ author       : PwC Team
* @date         : February 6, 2023
* @description  : To test the Batch Class TPM_AssortmentCreationBatch 
*******************************************************************************************************
Change History Story      Modified by               Date                          Desc

*******************************************************************************************************/
@isTest
public class TPM_AssortmentCreationBatchTest {
    
    public static final String DISPLAY_MSG = 'Assortment Record Not Created';
    public static final String IT_SALESORG = 'IT01';

    /****************************************************************************
    * @method         : executeTest
    * @description    : To test assortment header creation assignment batch execute method
    ****************************************************************************/
    
    @isTest
    public static void executeTest(){
       
        TPM_TestDataUtility.createProductDataWithTemplate(IT_SALESORG,'Product','Category',60);
        
       cgcloud__Product_Assortment_Template__c prodAssortmenttemplate = TPM_TestDataUtility.createProductAssortmentTemplate('Product',IT_SALESORG);
        insert prodAssortmenttemplate;
        
        cgcloud__Account_Template__c custTemplate = TPM_TestDataUtility.createCustomerTemplate(IT_SALESORG);
        insert custTemplate;
        
         Account superGroupAcc = TPM_TestDataUtility.createAccountWithTemplate('SuperGroup',IT_SALESORG,custTemplate.id);
        insert superGroupAcc;
        
        
        
        //TPM_AssortmentCreationBatch batchObj = new TPM_AssortmentCreationBatch();
        //Call the batch execute method
        //Database.executeBatch(batchObj,200);
        
        String cronexp = '0 0 0 * * ?';
        Test.startTest();
        String jobId = System.schedule('Scheduled Assortment creation batch at :'+system.now(),
                                       cronexp, 
                                       new TPM_AssortmentCreationScheduler());
        
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
                          NextFireTime
                          FROM CronTrigger WHERE id = :jobId];
        
        // Verify the expressions are the same
        System.assertEquals(cronexp, ct.CronExpression, 'True');
        
        
        Test.stopTest();
        
        //Check if assortment got created for the account created above :
        /*List<Account> accountList = [SELECT 	Id,
                                               			Name,
                                              			TPM_Is_Assortment_Created__c
                                               FROM   	Account 
                                               WHERE  	TPM_Hierarchy_Level__c='SuperGroup' LIMIT 1 ];
        System.assertEquals(false,!accountList[0].TPM_Is_Assortment_Created__c ,TPM_AssortmentCreationBatchTest.DISPLAY_MSG);*/
    }

}