force-app/main/default/objects/Account/fields/TPM_ProcessTPMCalculationChain__c.field-meta.xml
<CustomField>
    <fullName>TPM_ProcessTPMCalculationChain__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Executes the TPMCalculationChain batch.</description>
    <label>ProcessTPMCalculationChain</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cgcloud__Promotion__c/cgcloud__Promotion__c.object-meta.xml
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <label>Advanced Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advanced Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Promotion__c/fields/TPM_Phase__c.field-meta.xml
<CustomField>
    <fullName>TPM_Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Finance Edit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Promotion__c/fields/TPM_Promotion_Submitter__c.field-meta.xml
<CustomField>
    <fullName>TPM_Promotion_Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TPM_AdvancedPromotions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TPM_Approval__c/TPM_Approval__c.object-meta.xml
<CustomObject>
    <description>Custom object for Promotion &amp; Claim approvals</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Approvals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TPM_Approval__c/fields/TPM_Phase__c.field-meta.xml
<CustomField>
    <fullName>TPM_Phase__c</fullName>
    <description>Phase of the promotion</description>
    <label>Promotion Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preparation</fullName>
                <default>true</default>
                <label>Preparation</label>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Modeling</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>For Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Finance edit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TPM_Approval__c/fields/TPM_Promotion__c.field-meta.xml
<CustomField>
    <fullName>TPM_Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field for Promotion</description>
    <label>Promotion</label>
    <referenceTo>cgcloud__Promotion__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TPM_Approval__c/fields/TPM_Promotion_Submitter__c.field-meta.xml
<CustomField>
    <fullName>TPM_Promotion_Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TPM_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TPM_Approval__c/fields/TPM_Status__c.field-meta.xml
<CustomField>
    <fullName>TPM_Status__c</fullName>
    <description>Status of the Approval</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted for Approval</fullName>
                <default>true</default>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TPM_OpenAccess.cls
/*******************************************************************************************************
* @Name         : TPM_OpenAccess
* @Unit Test    : TPM_OpenAccessTest
* @Author       : PwC Team
* @Date         : 28/04/2023
* @description  : A Generic Without Sharing Class to perform DML without enforcing Object and Record
				  Sharing
*******************************************************************************************************/
public without sharing class TPM_OpenAccess {
    
    /*********************************************************************************************************
    @methodname   	getPromotionRelatedApprovals
    @createdDate  	28/04/2023
    @param     	  	promotionId
	@return 		List<TPM_Approval__c>
    @description  	Method to get the Promotion Related Approval Records.
    *********************************************************************************************************/
    public static List<TPM_Approval__c> getPromotionRelatedApprovals(Id promotionId){
        
        List<TPM_Approval__c> approvalRecordsList = [SELECT Id, 
                                              		 Name, 
                                              		 CreatedDate, 
                                              		 CreatedById, 
                                              		 CreatedBy.Name,
                                              	     TPM_Status__c,
                                                     TPM_Promotion_Submitter__c,
                                                     TPM_Promotion_Submitter__r.Name ,
                                                     TPM_Promotion__c, 
                                                     TPM_Phase__c,
                                                     OwnerId,
                                                     Owner.Name
                                              FROM   TPM_Approval__c 
                                              WHERE  TPM_Promotion__c =: promotionId];
        
            return approvalRecordsList;
    }
    
    /*********************************************************************************************************
    @methodname   	isUpdateAccountRecordFlag
    @createdDate  	May 10 2023
    @param     	  	objectRecordId
	@param			executeTPMCalculationChainBatch
	@return 		boolean
    @description  	Method to update the custom flag field on Account Record on Promotion After Save Process. 
    *********************************************************************************************************/
    public static boolean isUpdateAccountRecordFlag(String objectRecordId, Boolean executeTPMCalculationChainBatch){
        
        List<TPM_LoggerException.LogsWrapper> exceptionWrapperList =new List<TPM_LoggerException.LogsWrapper>();
        
        // Get the Promotion Record
        cgcloud__Promotion__c promoObj = [SELECT Id,
                                          		 Name,
                                          		 cgcloud__Anchor_Account__c
                                         FROM 	 cgcloud__Promotion__c
                                         WHERE 	 Id =:objectRecordId];
       
        // Get the Related Account for the Promotion Record
        Account accObj = [SELECT Id,
                          		 Name,
                          		 TPM_ProcessTPMCalculationChain__c
                          FROM   Account
                          WHERE  Id = : promoObj.cgcloud__Anchor_Account__c];
        
        // Check if the TPM_ProcessTPMCalculationChain__c already 
        // Set as True or not 
        if(accObj.TPM_ProcessTPMCalculationChain__c != TRUE){
            // If not True 
            // Check the field TPM_ProcessTPMCalculationChain__c
            accObj.TPM_ProcessTPMCalculationChain__c = TRUE;
            try{
                // Update the Account Record
                 update accObj;
                 executeTPMCalculationChainBatch = TRUE;
                 
            }catch(Exception exp){
                
                TPM_LoggerException.LogsWrapper logWrapperObj = new TPM_LoggerException.LogsWrapper();
                logWrapperObj.exceptionObj = exp;
                logWrapperObj.logLevel = TPM_ConstantsUtility.ERROR;
                logWrapperObj.className = TPM_ConstantsUtility.TPM_PROMOTION_MAIN_CARD_CONTROLLER;
                logWrapperObj.methodName = TPM_ConstantsUtility.EXECUTE_TPM_CACULATION_CHAIN_BATCH;
                exceptionWrapperList.add(logWrapperObj);
                TPM_LoggerException.log(exceptionWrapperList);
            } 
        }
        
        return executeTPMCalculationChainBatch;
    }
}