force-app/main/default/objects/Account/fields/TPM_Sector__c.field-meta.xml
<CustomField>
    <fullName>TPM_Sector__c</fullName>
    <description>Sector of the customer</description>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TPM_Segment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Segment__c</fullName>
    <description>Segment of the customer</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TPM_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Subsegment__c</fullName>
    <description>SubSegment of the customer</description>
    <label>Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Subsegment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Account_Plan__c/cgcloud__Account_Plan__c.object-meta.xml
<CustomObject>
    <description>Container for Account Data for one Planning Account, one Business Year and one or multiple Categories.</description>
    <label>Customer Business Plan</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Account_Plan__c/fields/TPM_Sector__c.field-meta.xml
<CustomField>
    <fullName>TPM_Sector__c</fullName>
    <description>Sector of the customer</description>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Account_Plan__c/fields/TPM_Segment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Segment__c</fullName>
    <description>Segment of the customer</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Account_Plan__c/fields/TPM_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>TPM_Subsegment__c</fullName>
    <description>SubSegment of the customer</description>
    <label>Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TPM_Subsegment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TPM_Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>ASIA</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>B2B</fullName>
    </customValue>
    <customValue>
        <fullName>Portable power</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <description>Sector of the customer</description>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TPM_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FOOD_DRUG</fullName>
    </customValue>
    <customValue>
        <fullName>TI</fullName>
    </customValue>
    <customValue>
        <fullName>DOA</fullName>
    </customValue>
    <customValue>
        <fullName>Russia</fullName>
    </customValue>
    <customValue>
        <fullName>NCE</fullName>
    </customValue>
    <customValue>
        <fullName>BNL</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>CLUB</fullName>
    </customValue>
    <customValue>
        <fullName>MEXICO</fullName>
    </customValue>
    <customValue>
        <fullName>BRAZIL</fullName>
    </customValue>
    <customValue>
        <fullName>LADEX</fullName>
    </customValue>
    <customValue>
        <fullName>CHINA</fullName>
    </customValue>
    <customValue>
        <fullName>AADO</fullName>
    </customValue>
    <customValue>
        <fullName>South Korea</fullName>
    </customValue>
    <customValue>
        <fullName>WALM_MASS</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon</fullName>
    </customValue>
    <customValue>
        <fullName>Portable power</fullName>
    </customValue>
    <customValue>
        <fullName>HOME_HW</fullName>
    </customValue>
    <customValue>
        <fullName>ALT</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>B2B America</fullName>
    </customValue>
    <customValue>
        <fullName>B2B International</fullName>
    </customValue>
    <customValue>
        <fullName>CHILE</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>UK&amp;I</fullName>
    </customValue>
    <description>Segment of the customer</description>
    <masterLabel>Segment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TPM_Subsegment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alternative</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Australia/NewZealand</fullName>
    </customValue>
    <customValue>
        <fullName>BNL</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Central Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Club</fullName>
    </customValue>
    <customValue>
        <fullName>Costco</fullName>
    </customValue>
    <customValue>
        <fullName>DACH</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor Operation</fullName>
    </customValue>
    <customValue>
        <fullName>Drug</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai Hub</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Global OEM</fullName>
    </customValue>
    <customValue>
        <fullName>Home/Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>LA Comm Oth</fullName>
    </customValue>
    <customValue>
        <fullName>Mass</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>OEM Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>P. AFTMKT AMERICAS</fullName>
    </customValue>
    <customValue>
        <fullName>P. AFTMKT ASIA</fullName>
    </customValue>
    <customValue>
        <fullName>P. AFTMKT EUROPE</fullName>
    </customValue>
    <customValue>
        <fullName>P. OEM ASIA</fullName>
    </customValue>
    <customValue>
        <fullName>P. OEM EUROPE</fullName>
    </customValue>
    <description>SubSegment of the customer</description>
    <masterLabel>Subsegment</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TPM_AccountPlanTriggerHelper.cls
/******************************************************************************************************
@Name            TPM_AccountPlanTriggerHelper
@testclass       TPM_PromotionCustomerPlanTriggerTest
@Author          PwC Team
@date            January 27, 2023
@description     Handles business logic for Customer Business Plan Trigger Handler 
*******************************************************************************************************
Change History Story      Modified by               Date                          Desc

*******************************************************************************************************/

public inherited sharing class TPM_AccountPlanTriggerHelper {
    
    // List to log errors/exceptions 
    public static List<TPM_LoggerException.LogsWrapper> exceptionWrapperList;
    
    /***************************************************************************************************
	@description	default private constructor
	****************************************************************************************************/
    @SuppressWarnings('PMD.EmptyStatementBlock')
    private TPM_AccountPlanTriggerHelper() { 
        
    }
    
    /********************************************************************************************************** 
	@methodname 	 extendCBPSharingForAccountTeamMembers
	@param           newMap
	@param           oldMap
	@description	 method handles the process to share all CBP Records on insert/update related to account with team members 
	***********************************************************************************************************/  
    public static void extendCBPSharingForAccountTeamMembers(Map<Id, SObject> newMap, Map<Id, SObject> oldMap){
        
        // initializing log WrapperList 
        exceptionWrapperList = new List<TPM_LoggerException.LogsWrapper>();

        // preparing map of new cbp ids and account id for processing
        Map<Id, Id> newCBPIdandAcntIdMap = new Map<Id, Id>();
        
        try{
            Map<Id, cgcloud__Account_Plan__c> cbpOldMap = (Map<Id, cgcloud__Account_Plan__c>)oldMap;

            // iterating over newly created cbp records to prepare map to store cbpid and parentids
            for(cgcloud__Account_Plan__c cbpObj : (List<cgcloud__Account_Plan__c>)newMap.Values()){
                
                if(Trigger.isInsert || (cbpOldMap.get(cbpObj.Id).cgcloud__Account__c != cbpObj.cgcloud__Account__c)){ 
                    // If the parent account is not already in the map, add it
                    if(!newCBPIdandAcntIdMap.containsKey(cbpObj.Id) && cbpObj.cgcloud__Account__c != null){
                        newCBPIdandAcntIdMap.put(cbpObj.Id, cbpObj.cgcloud__Account__c);
                    } 
                }
            }            
			
            if(!newCBPIdandAcntIdMap.isEmpty()){
                TPM_RecordSharingUtils.handleChildSharingForAccountsTeamMembers(newCBPIdandAcntIdMap, TPM_ConstantsUtility.ACCOUNTPLAN_SHARE, exceptionWrapperList,  TPM_ConstantsUtility.TRIGGER_ACCOUNTPLAN_HELPER);
            }
 
        }
        catch(Exception exp){
            TPM_LoggerException.LogsWrapper logWrapperObj = new TPM_LoggerException.LogsWrapper();
            logWrapperObj.exceptionObj = exp;
            logWrapperObj.logLevel = TPM_ConstantsUtility.FATAL;
            exceptionWrapperList.add(logWrapperObj);
            
            // Call the TPM_LoggerException class log method to save all the exception details during insert
            TPM_LoggerException.log(exceptionWrapperList);
        }
    }
    
    /********************************************************************************************************** 
	@methodname 	 handleFieldUpdatesForSVF
	@param           svfToCreateList
	@description	 method handles field upddates for svf records from the related account record
	***********************************************************************************************************/
    
     //bypassing since this ruleset is not applicable because the target and destination instance is different: 
    @SuppressWarnings('PMD.IdempotentOperations')
    
    public static void handleFieldUpdatesForSVF(List<SObject> svfToCreateList){ 
        
        Set<Id> accountIdSet = new Set<Id>();
		Map<Id,Account> accountRecordMap = new Map<Id,Account>();
		
        for(cgcloud__Account_Plan__c svfObj : (List<cgcloud__Account_Plan__c>) svfToCreateList){
            
			accountIdSet.add(svfObj.cgcloud__Account__c);
        }
		
		for(Account accountObj : [SELECT
								  Id,
								  Name,
								  TPM_Segment__c,
								  TPM_Subsegment__c,
								  TPM_Sector__c
                                  FROM Account
                                  WHERE Id in:accountIdSet]){
								  
			accountRecordMap.put(accountObj.Id, accountObj);
		}
		
		
		for(cgcloud__Account_Plan__c svfObj : (List<cgcloud__Account_Plan__c>) svfToCreateList){
				
				if(accountRecordMap.containskey(svfObj.cgcloud__Account__c)){
				
					svfObj.TPM_Segment__c = accountRecordMap.get(svfObj.cgcloud__Account__c).TPM_Segment__c;
					svfObj.TPM_Subsegment__c = accountRecordMap.get(svfObj.cgcloud__Account__c).TPM_Subsegment__c;
					svfObj.TPM_Sector__c = accountRecordMap.get(svfObj.cgcloud__Account__c).TPM_Sector__c;
				}
				
		}
    }

    
}