force-app/main/default/objects/TPM_ConfigureNightlyBatch__mdt/TPM_ConfigureNightlyBatch__mdt.object-meta.xml
<CustomObject>
    <description>To Configure the TPMCalculationChain NightlyBatch</description>
    <label>TPM_ConfigureNightlyBatch</label>
    <pluralLabel>TPM_ConfigureNightlyBatchs</pluralLabel>
</CustomObject>

force-app/main/default/objects/TPM_ConfigureNightlyBatch__mdt/fields/TPM_execAccountPlanBasic__c.field-meta.xml
<CustomField>
    <fullName>TPM_execAccountPlanBasic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TPM_execAccountPlanBasic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TPM_ConfigureNightlyBatch__mdt/fields/TPM_execAccountPlanBusinessPlan__c.field-meta.xml
<CustomField>
    <fullName>TPM_execAccountPlanBusinessPlan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TPM_execAccountPlanBusinessPlan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TPM_ConfigureNightlyBatch__mdt/fields/TPM_execAccountProductList__c.field-meta.xml
<CustomField>
    <fullName>TPM_execAccountProductList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TPM_execAccountProductList</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TPM_ConfigureNightlyBatch__mdt/fields/TPM_execFundCalculation__c.field-meta.xml
<CustomField>
    <fullName>TPM_execFundCalculation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TPM_execFundCalculation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TPM_ConfigureNightlyBatch__mdt/fields/TPM_execPromotion__c.field-meta.xml
<CustomField>
    <fullName>TPM_execPromotion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TPM_execPromotion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TPM_ConfigureNightlyBatch__mdt/fields/TPM_execRBFCalculation__c.field-meta.xml
<CustomField>
    <fullName>TPM_execRBFCalculation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TPM_execRBFCalculation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TPM_ConfigureNightlyBatch__mdt/fields/TPM_execReorganization__c.field-meta.xml
<CustomField>
    <fullName>TPM_execReorganization__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TPM_execReorganization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TPM_ConfigureNightlyBatch__mdt/fields/TPM_PAAPLA_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>TPM_PAAPLA_Batch_Size__c</fullName>
    <label>TPM_PAAPLA_Batch_Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TPM_ConfigureNightlyBatch__mdt/fields/TPM_Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>TPM_Sales_Org__c</fullName>
    <label>TPM_Sales_Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TPM_US01NightlyQueue.cls
/*******************************************************************************************************
* @Name         : TPM_US01NightlyQueue
* @testclass    : TPM_US01NightlyQueueTest
* @Author       : PwC Team
* @date         : April 10, 2023
* @description  : Queuable Apex is used to excute the US01 TPMCalculationChain Nightly Batches.
*******************************************************************************************************
Change History Story      Modified by               Date                          Desc

*******************************************************************************************************/
public class TPM_US01NightlyQueue implements Queueable, Database.AllowsCallouts{
    /*********************************************************************************
    * @method         : execute
    * @param            qc
    * @description    : Queue execute method to fetch the account records with 
    * 					salesOrg = US01 and Process and Call TPMCalculationChain Batch
    **********************************************************************************/
    public void execute(QueueableContext qc) {
        
        TPM_ConfigureNightlyBatch__mdt nightlyBatchCMDT = TPM_ConfigureNightlyBatch__mdt.getInstance(TPM_ConstantsUtility.TPM_EXECUTE_US01_NIGHTLY_BATCH);
        
        // Initialize the Nightly Batch Settings
        cgcloud.TPM_BC_Settings settings = new cgcloud.TPM_BC_Settings(nightlyBatchCMDT.TPM_Sales_Org__c);
        settings.execReorganization = nightlyBatchCMDT.TPM_execReorganization__c;
        settings.execAccountProductList = nightlyBatchCMDT.TPM_execAccountProductList__c;
        settings.execAccountPlanBasic = nightlyBatchCMDT.TPM_execAccountPlanBasic__c;
        settings.execPromotion = nightlyBatchCMDT.TPM_execPromotion__c;
        settings.execAccountPlanBusinessPlan = nightlyBatchCMDT.TPM_execAccountPlanBusinessPlan__c;
        settings.execRBFCalculation = nightlyBatchCMDT.TPM_execRBFCalculation__c;
        settings.execFundCalculation = nightlyBatchCMDT.TPM_execFundCalculation__c;
        settings.batchSizePAAPLA = (Integer.valueOf(nightlyBatchCMDT.TPM_PAAPLA_Batch_Size__c));
        
        // Instantiate the TPMCalculationChain Class
        cgcloud.TPMCalculationChain c = new cgcloud.TPMCalculationChain(settings);
        
        if(!Test.isRunningTest()){
            // Start the TPMCalculationChain Process
            c.startProcess();  
        }
        
    }

}